using System;
using System.Drawing;
using System.Windows.Forms;

namespace BKS;

partial class ConnectionSettingsForm
{
    private System.ComponentModel.IContainer components = null;

    private TextBox server;
    private TextBox database;
    private TextBox user;
    private TextBox password;
    private TextBox api;
    private CheckBox integrated;
    private CheckBox trust;
    private TableLayoutPanel pnlDatabase;
    private Label lbl_server;
    private Label lbl_database;
    private Label lbl_user;
    private Label lbl_password;
    private Label lbl_integrated;
    private Label lbl_trust;
    private TableLayoutPanel pnlApi;
    private Label lbl_api;
    private TabControl tabSettings;
    private TabPage tabDatabase;
    private TabPage tabApi;
    private TableLayoutPanel pnlRoot;
    private TableLayoutPanel pnlHeader;
    private Label lblTitle;
    private Label lblSubtitle;
    private FlowLayoutPanel pnlCommandBar;
    private Button btnSave;
    private Button btnCancel;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        server = new TextBox();
        database = new TextBox();
        user = new TextBox();
        password = new TextBox();
        api = new TextBox();
        integrated = new CheckBox();
        trust = new CheckBox();
        pnlDatabase = new TableLayoutPanel();
        lbl_server = new Label();
        lbl_database = new Label();
        lbl_user = new Label();
        lbl_password = new Label();
        lbl_integrated = new Label();
        lbl_trust = new Label();
        pnlApi = new TableLayoutPanel();
        lbl_api = new Label();
        tabSettings = new TabControl();
        tabDatabase = new TabPage();
        tabApi = new TabPage();
        pnlRoot = new TableLayoutPanel();
        pnlHeader = new TableLayoutPanel();
        lblTitle = new Label();
        lblSubtitle = new Label();
        pnlCommandBar = new FlowLayoutPanel();
        btnSave = new Button();
        btnCancel = new Button();
        SuspendLayout();
        pnlDatabase.SuspendLayout();
        pnlApi.SuspendLayout();
        tabSettings.SuspendLayout();
        tabDatabase.SuspendLayout();
        tabApi.SuspendLayout();
        pnlRoot.SuspendLayout();
        pnlHeader.SuspendLayout();
        pnlCommandBar.SuspendLayout();
        server.Name = "server";
        server.Dock = DockStyle.Fill;
        server.Margin = new Padding(0, 0, 16, 10);
        server.Size = new Size(260, 32);
        server.TabIndex = 1;
        server.Font = new Font("Segoe UI", 10F);
        server.ForeColor = Color.FromArgb(37, 54, 75);
        server.BorderStyle = BorderStyle.FixedSingle;
        database.Name = "database";
        database.Dock = DockStyle.Fill;
        database.Margin = new Padding(0, 0, 16, 10);
        database.Size = new Size(260, 32);
        database.TabIndex = 2;
        database.Font = new Font("Segoe UI", 10F);
        database.ForeColor = Color.FromArgb(37, 54, 75);
        database.BorderStyle = BorderStyle.FixedSingle;
        user.Name = "user";
        user.Dock = DockStyle.Fill;
        user.Margin = new Padding(0, 0, 16, 10);
        user.Size = new Size(260, 32);
        user.TabIndex = 3;
        user.Font = new Font("Segoe UI", 10F);
        user.ForeColor = Color.FromArgb(37, 54, 75);
        user.BorderStyle = BorderStyle.FixedSingle;
        password.Name = "password";
        password.Dock = DockStyle.Fill;
        password.Margin = new Padding(0, 0, 16, 10);
        password.Size = new Size(260, 32);
        password.TabIndex = 4;
        password.Font = new Font("Segoe UI", 10F);
        password.ForeColor = Color.FromArgb(37, 54, 75);
        password.BorderStyle = BorderStyle.FixedSingle;
        api.Name = "api";
        api.Dock = DockStyle.Fill;
        api.Margin = new Padding(0, 0, 16, 10);
        api.Size = new Size(260, 32);
        api.TabIndex = 5;
        api.Font = new Font("Segoe UI", 10F);
        api.ForeColor = Color.FromArgb(37, 54, 75);
        api.BorderStyle = BorderStyle.FixedSingle;
        integrated.Name = "integrated";
        integrated.AutoSize = true;
        integrated.Anchor = AnchorStyles.Left;
        integrated.Margin = new Padding(0, 3, 16, 6);
        integrated.Text = "Windows kimliği";
        trust.Name = "trust";
        trust.AutoSize = true;
        trust.Anchor = AnchorStyles.Left;
        trust.Margin = new Padding(0, 3, 16, 6);
        trust.Text = "Sunucu sertifikasına güven";
        password.UseSystemPasswordChar = true;
        pnlDatabase.Name = "pnlDatabase";
        pnlDatabase.Dock = DockStyle.Fill;
        pnlDatabase.ColumnCount = 2;
        pnlDatabase.RowCount = 7;
        pnlDatabase.Margin = Padding.Empty;
        pnlDatabase.Padding = new Padding(16);
        pnlDatabase.BackColor = Color.White;
        pnlDatabase.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        pnlDatabase.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        pnlDatabase.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        pnlDatabase.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        pnlDatabase.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        pnlDatabase.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        pnlDatabase.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        pnlDatabase.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        pnlDatabase.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlDatabase.AutoScroll = true;
        lbl_server.Name = "lbl_server";
        lbl_server.AutoSize = true;
        lbl_server.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_server.Margin = new Padding(0, 2, 12, 6);
        lbl_server.Text = "Sunucu";
        lbl_database.Name = "lbl_database";
        lbl_database.AutoSize = true;
        lbl_database.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_database.Margin = new Padding(0, 2, 12, 6);
        lbl_database.Text = "Veritabanı";
        lbl_user.Name = "lbl_user";
        lbl_user.AutoSize = true;
        lbl_user.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_user.Margin = new Padding(0, 2, 12, 6);
        lbl_user.Text = "Kullanıcı";
        lbl_password.Name = "lbl_password";
        lbl_password.AutoSize = true;
        lbl_password.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_password.Margin = new Padding(0, 2, 12, 6);
        lbl_password.Text = "Parola";
        lbl_integrated.Name = "lbl_integrated";
        lbl_integrated.AutoSize = true;
        lbl_integrated.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_integrated.Margin = new Padding(0, 2, 12, 6);
        lbl_integrated.Text = "Kimlik doğrulama";
        lbl_trust.Name = "lbl_trust";
        lbl_trust.AutoSize = true;
        lbl_trust.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_trust.Margin = new Padding(0, 2, 12, 6);
        lbl_trust.Text = "Sertifika";
        pnlApi.Name = "pnlApi";
        pnlApi.Dock = DockStyle.Fill;
        pnlApi.ColumnCount = 1;
        pnlApi.RowCount = 3;
        pnlApi.Margin = Padding.Empty;
        pnlApi.Padding = new Padding(16);
        pnlApi.BackColor = Color.White;
        pnlApi.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100.0F));
        pnlApi.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        pnlApi.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        pnlApi.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlApi.AutoScroll = true;
        lbl_api.Name = "lbl_api";
        lbl_api.AutoSize = true;
        lbl_api.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_api.Margin = new Padding(0, 2, 12, 6);
        lbl_api.Text = "Hizmet adresi (HTTPS)";
        tabSettings.Name = "tabSettings";
        tabSettings.Dock = DockStyle.Fill;
        tabSettings.Padding = new Point(14, 7);
        tabSettings.SelectedIndex = 0;
        tabDatabase.Name = "tabDatabase";
        tabDatabase.Text = "Veritabanı";
        tabDatabase.Padding = new Padding(4);
        tabDatabase.BackColor = Color.White;
        tabDatabase.AutoScroll = true;
        tabApi.Name = "tabApi";
        tabApi.Text = "Giriş Hizmeti";
        tabApi.Padding = new Padding(4);
        tabApi.BackColor = Color.White;
        tabApi.AutoScroll = true;
        pnlRoot.Name = "pnlRoot";
        pnlRoot.Dock = DockStyle.Fill;
        pnlRoot.ColumnCount = 1;
        pnlRoot.RowCount = 3;
        pnlRoot.Margin = Padding.Empty;
        pnlRoot.BackColor = Color.White;
        pnlRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 62F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlRoot.Padding = Padding.Empty;
        pnlHeader.Name = "pnlHeader";
        pnlHeader.Dock = DockStyle.Fill;
        pnlHeader.ColumnCount = 1;
        pnlHeader.RowCount = 2;
        pnlHeader.Margin = Padding.Empty;
        pnlHeader.BackColor = Color.White;
        pnlHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlHeader.Padding = new Padding(16, 6, 16, 0);
        lblTitle.Name = "lblTitle";
        lblTitle.ForeColor = Color.FromArgb(68, 87, 111);
        lblTitle.Margin = new Padding(0, 2, 12, 6);
        lblTitle.Text = "BKS Bağlantı Ayarları";
        lblTitle.Font = new Font("Segoe UI Semibold", 15F);
        lblTitle.AutoSize = true;
        lblSubtitle.Name = "lblSubtitle";
        lblSubtitle.ForeColor = Color.FromArgb(68, 87, 111);
        lblSubtitle.Margin = new Padding(0, 2, 12, 6);
        lblSubtitle.Text = "Bilgileri düzenleyin; değişikliklerinizi kaydedin.";
        lblSubtitle.AutoSize = true;
        pnlCommandBar.Name = "pnlCommandBar";
        pnlCommandBar.Dock = DockStyle.Top;
        pnlCommandBar.AutoSize = true;
        pnlCommandBar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlCommandBar.WrapContents = true;
        pnlCommandBar.Padding = new Padding(16, 8, 8, 8);
        pnlCommandBar.Margin = Padding.Empty;
        pnlCommandBar.BackColor = Color.White;
        btnSave.Name = "btnSave";
        btnSave.AutoSize = true;
        btnSave.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnSave.MinimumSize = new Size(96, 34);
        btnSave.Padding = new Padding(12, 4, 12, 4);
        btnSave.Margin = new Padding(0, 0, 8, 0);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.BackColor = Color.FromArgb(40, 99, 163);
        btnSave.ForeColor = Color.White;
        btnSave.UseVisualStyleBackColor = false;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnSave.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnSave.Text = "Kaydet";
        btnCancel.Name = "btnCancel";
        btnCancel.AutoSize = true;
        btnCancel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnCancel.MinimumSize = new Size(96, 34);
        btnCancel.Padding = new Padding(12, 4, 12, 4);
        btnCancel.Margin = new Padding(0, 0, 8, 0);
        btnCancel.FlatStyle = FlatStyle.Flat;
        btnCancel.BackColor = Color.FromArgb(246, 248, 251);
        btnCancel.ForeColor = Color.FromArgb(37, 54, 75);
        btnCancel.UseVisualStyleBackColor = false;
        btnCancel.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnCancel.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnCancel.Text = "Vazgeç";
        pnlDatabase.Controls.Add(lbl_server, 0, 0);
        pnlDatabase.Controls.Add(server, 0, 1);
        pnlDatabase.Controls.Add(lbl_database, 1, 0);
        pnlDatabase.Controls.Add(database, 1, 1);
        pnlDatabase.Controls.Add(lbl_user, 0, 2);
        pnlDatabase.Controls.Add(user, 0, 3);
        pnlDatabase.Controls.Add(lbl_password, 1, 2);
        pnlDatabase.Controls.Add(password, 1, 3);
        pnlDatabase.Controls.Add(lbl_integrated, 0, 4);
        pnlDatabase.Controls.Add(integrated, 0, 5);
        pnlDatabase.Controls.Add(lbl_trust, 1, 4);
        pnlDatabase.Controls.Add(trust, 1, 5);
        pnlApi.Controls.Add(lbl_api, 0, 0);
        pnlApi.Controls.Add(api, 0, 1);
        tabDatabase.Controls.Add(pnlDatabase);
        tabSettings.Controls.Add(tabDatabase);
        tabApi.Controls.Add(pnlApi);
        tabSettings.Controls.Add(tabApi);
        pnlHeader.Controls.Add(lblTitle, 0, 0);
        pnlHeader.Controls.Add(lblSubtitle, 0, 1);
        pnlRoot.Controls.Add(pnlHeader, 0, 0);
        pnlCommandBar.Controls.Add(btnSave);
        pnlCommandBar.Controls.Add(btnCancel);
        pnlRoot.Controls.Add(pnlCommandBar, 0, 1);
        pnlRoot.Controls.Add(tabSettings, 0, 2);
        Controls.Add(pnlRoot);
        btnSave.Click += Save_Click;
        btnCancel.Click += Cancel_Click;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.White;
        ClientSize = new Size(1120, 760);
        MinimumSize = new Size(720, 520);
        StartPosition = FormStartPosition.CenterParent;
        KeyPreview = true;
        Name = "ConnectionSettingsForm";
        Text = "BKS Bağlantı Ayarları";
        pnlCommandBar.ResumeLayout(false);
        pnlCommandBar.PerformLayout();
        pnlHeader.ResumeLayout(false);
        pnlHeader.PerformLayout();
        pnlRoot.ResumeLayout(false);
        pnlRoot.PerformLayout();
        tabApi.ResumeLayout(false);
        tabApi.PerformLayout();
        tabDatabase.ResumeLayout(false);
        tabDatabase.PerformLayout();
        tabSettings.ResumeLayout(false);
        tabSettings.PerformLayout();
        pnlApi.ResumeLayout(false);
        pnlApi.PerformLayout();
        pnlDatabase.ResumeLayout(false);
        pnlDatabase.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }
    #endregion
}
