using System;
using System.Drawing;
using System.Windows.Forms;

namespace BKS;

partial class DataListForm
{
    private System.ComponentModel.IContainer components = null;

    private DataGridView grid;
    private TableLayoutPanel pnlList;
    private TableLayoutPanel pnlListToolbar;
    private Label pnlListTitle;
    private TextBox txtSearch;
    private Button pnlListClear;
    private Button pnlListColumns;
    private Label pnlListCount;
    private TableLayoutPanel pnlRoot;
    private TableLayoutPanel pnlHeader;
    private Label lblTitle;
    private Label lblSubtitle;
    private TableLayoutPanel pnlDetails;
    private Label lblDetails;
    private DataGridView detailGrid;
    private FlowLayoutPanel pnlCommandBar;
    private Button btnRefresh;
    private Button btnClose;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        grid = new DataGridView();
        grid.MultiSelect = false;
        pnlList = new TableLayoutPanel();
        pnlListToolbar = new TableLayoutPanel();
        pnlListTitle = new Label();
        txtSearch = new TextBox();
        pnlListClear = new Button();
        pnlListColumns = new Button();
        pnlListCount = new Label();
        pnlRoot = new TableLayoutPanel();
        pnlHeader = new TableLayoutPanel();
        lblTitle = new Label();
        lblSubtitle = new Label();
        pnlDetails = new TableLayoutPanel();
        lblDetails = new Label();
        detailGrid = new DataGridView();
        pnlCommandBar = new FlowLayoutPanel();
        btnRefresh = new Button();
        btnClose = new Button();
        ((System.ComponentModel.ISupportInitialize)grid).BeginInit();
        SuspendLayout();
        pnlList.SuspendLayout();
        pnlListToolbar.SuspendLayout();
        pnlRoot.SuspendLayout();
        pnlHeader.SuspendLayout();
        pnlCommandBar.SuspendLayout();
        grid.Name = "grid";
        grid.Dock = DockStyle.Fill;
        grid.BackgroundColor = Color.FromArgb(239, 247, 253);
        grid.BorderStyle = BorderStyle.None;
        grid.EnableHeadersVisualStyles = false;
        grid.ColumnHeadersHeight = 36;
        grid.RowHeadersWidth = 44;
        grid.AllowUserToAddRows = false;
        grid.AllowUserToDeleteRows = false;
        grid.ReadOnly = true;
        grid.AllowUserToOrderColumns = true;
        grid.AllowUserToResizeRows = false;
        grid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        grid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        grid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(218, 236, 250);
        grid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI Semibold", 9.5F);
        grid.ColumnHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(218, 236, 250);
        grid.DefaultCellStyle.Font = new Font("Segoe UI", 9.5F);
        grid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(200, 224, 246);
        grid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(37, 54, 75);
        grid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(239, 247, 253);
        grid.RowTemplate.Height = 32;
        pnlList.Name = "pnlList";
        pnlList.Dock = DockStyle.Fill;
        pnlList.ColumnCount = 1;
        pnlList.RowCount = 3;
        pnlList.Margin = Padding.Empty;
        pnlList.BackColor = Color.FromArgb(239, 247, 253);
        pnlList.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlList.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlList.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlList.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        pnlList.Padding = new Padding(8);
        pnlListToolbar.Name = "pnlListToolbar";
        pnlListToolbar.ColumnCount = 4;
        pnlListToolbar.RowCount = 1;
        pnlListToolbar.Margin = Padding.Empty;
        pnlListToolbar.BackColor = Color.FromArgb(218, 236, 250);
        pnlListToolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlListToolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 230F));
        pnlListToolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 112F));
        pnlListToolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 112F));
        pnlListToolbar.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        pnlListToolbar.Padding = Padding.Empty;
        pnlListToolbar.AutoSize = true;
        pnlListToolbar.Dock = DockStyle.Top;
        pnlListTitle.Name = "pnlListTitle";
        pnlListTitle.ForeColor = Color.FromArgb(68, 87, 111);
        pnlListTitle.Margin = new Padding(0, 2, 12, 6);
        pnlListTitle.Text = "İşlem geçmişi";
        pnlListTitle.Font = new Font("Segoe UI Semibold", 11F);
        pnlListTitle.Anchor = AnchorStyles.Left;
        pnlListTitle.AutoEllipsis = true;
        pnlListTitle.AutoSize = false;
        pnlListTitle.Dock = DockStyle.Fill;
        txtSearch.Name = "txtSearch";
        txtSearch.Dock = DockStyle.Fill;
        txtSearch.Size = new Size(260, 32);
        txtSearch.TabIndex = 5;
        txtSearch.Font = new Font("Segoe UI", 10F);
        txtSearch.ForeColor = Color.FromArgb(37, 54, 75);
        txtSearch.BorderStyle = BorderStyle.FixedSingle;
        txtSearch.PlaceholderText = "Listede ara (Ctrl+F)";
        txtSearch.Margin = new Padding(0, 4, 8, 6);
        pnlListClear.Name = "pnlListClear";
        pnlListClear.AutoSize = true;
        pnlListClear.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlListClear.MinimumSize = new Size(96, 34);
        pnlListClear.Padding = new Padding(12, 4, 12, 4);
        pnlListClear.Margin = new Padding(0, 0, 8, 0);
        pnlListClear.FlatStyle = FlatStyle.Flat;
        pnlListClear.BackColor = Color.FromArgb(246, 248, 251);
        pnlListClear.ForeColor = Color.FromArgb(37, 54, 75);
        pnlListClear.UseVisualStyleBackColor = false;
        pnlListClear.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        pnlListClear.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        pnlListClear.Text = "Temizle";
        pnlListColumns.Name = "pnlListColumns";
        pnlListColumns.AutoSize = true;
        pnlListColumns.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlListColumns.MinimumSize = new Size(96, 34);
        pnlListColumns.Padding = new Padding(12, 4, 12, 4);
        pnlListColumns.Margin = new Padding(0, 0, 8, 0);
        pnlListColumns.FlatStyle = FlatStyle.Flat;
        pnlListColumns.BackColor = Color.FromArgb(246, 248, 251);
        pnlListColumns.ForeColor = Color.FromArgb(37, 54, 75);
        pnlListColumns.UseVisualStyleBackColor = false;
        pnlListColumns.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        pnlListColumns.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        pnlListColumns.Text = "Sütunlar";
        pnlListCount.Name = "pnlListCount";
        pnlListCount.AutoSize = true;
        pnlListCount.ForeColor = Color.FromArgb(68, 87, 111);
        pnlListCount.Margin = new Padding(0, 2, 12, 6);
        pnlListCount.Text = "Kayıt: 0";
        pnlListCount.Dock = DockStyle.Fill;
        pnlRoot.Name = "pnlRoot";
        pnlRoot.Dock = DockStyle.Fill;
        pnlRoot.ColumnCount = 1;
        pnlRoot.RowCount = 4;
        pnlRoot.Margin = Padding.Empty;
        pnlRoot.BackColor = Color.FromArgb(228, 241, 252);
        pnlRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 78F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 60F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 40F));
        pnlRoot.Padding = Padding.Empty;
        pnlHeader.Name = "pnlHeader";
        pnlHeader.Dock = DockStyle.Fill;
        pnlHeader.ColumnCount = 1;
        pnlHeader.RowCount = 2;
        pnlHeader.Margin = Padding.Empty;
        pnlHeader.BackColor = Color.FromArgb(218, 236, 250);
        pnlHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlHeader.Padding = new Padding(16, 6, 16, 0);
        lblTitle.Name = "lblTitle";
        lblTitle.ForeColor = Color.FromArgb(68, 87, 111);
        lblTitle.Margin = new Padding(0, 2, 12, 6);
        lblTitle.Text = "İşlem Geçmişi";
        lblTitle.Font = new Font("Segoe UI Semibold", 15F);
        lblTitle.AutoSize = true;
        lblSubtitle.Name = "lblSubtitle";
        lblSubtitle.ForeColor = Color.FromArgb(68, 87, 111);
        lblSubtitle.Margin = new Padding(0, 2, 12, 6);
        lblSubtitle.Text = "Bu bölümdeki tüm işlemler listelenir. Ayrıntıları görmek için bir satır seçin.";
        lblSubtitle.AutoSize = true;
        pnlCommandBar.Name = "pnlCommandBar";
        pnlCommandBar.Dock = DockStyle.Top;
        pnlCommandBar.AutoSize = true;
        pnlCommandBar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlCommandBar.WrapContents = true;
        pnlCommandBar.Padding = new Padding(16, 8, 8, 8);
        pnlCommandBar.Margin = Padding.Empty;
        pnlCommandBar.BackColor = Color.FromArgb(228, 241, 252);
        btnRefresh.Name = "btnRefresh";
        btnRefresh.AutoSize = true;
        btnRefresh.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnRefresh.MinimumSize = new Size(96, 34);
        btnRefresh.Padding = new Padding(12, 4, 12, 4);
        btnRefresh.Margin = new Padding(0, 0, 8, 0);
        btnRefresh.FlatStyle = FlatStyle.Flat;
        btnRefresh.BackColor = Color.FromArgb(40, 99, 163);
        btnRefresh.ForeColor = Color.White;
        btnRefresh.UseVisualStyleBackColor = false;
        btnRefresh.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        btnRefresh.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnRefresh.Text = "Yenile";
        btnClose.Name = "btnClose";
        btnClose.AutoSize = true;
        btnClose.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnClose.MinimumSize = new Size(96, 34);
        btnClose.Padding = new Padding(12, 4, 12, 4);
        btnClose.Margin = new Padding(0, 0, 8, 0);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.BackColor = Color.FromArgb(246, 248, 251);
        btnClose.ForeColor = Color.FromArgb(37, 54, 75);
        btnClose.UseVisualStyleBackColor = false;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        btnClose.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnClose.Text = "Kapat";
        pnlListToolbar.Controls.Add(pnlListTitle, 0, 0);
        pnlListToolbar.Controls.Add(txtSearch, 1, 0);
        pnlListToolbar.Controls.Add(pnlListClear, 2, 0);
        pnlListToolbar.Controls.Add(pnlListColumns, 3, 0);
        pnlList.Controls.Add(pnlListToolbar, 0, 0);
        pnlList.Controls.Add(grid, 0, 1);
        pnlList.Controls.Add(pnlListCount, 0, 2);
        pnlHeader.Controls.Add(lblTitle, 0, 0);
        pnlHeader.Controls.Add(lblSubtitle, 0, 1);
        pnlRoot.Controls.Add(pnlHeader, 0, 0);
        pnlCommandBar.Controls.Add(btnRefresh);
        pnlCommandBar.Controls.Add(btnClose);
        pnlRoot.Controls.Add(pnlCommandBar, 0, 1);
        pnlRoot.Controls.Add(pnlList, 0, 2);
        pnlDetails.Name = "pnlDetails";
        pnlDetails.Dock = DockStyle.Fill;
        pnlDetails.ColumnCount = 1;
        pnlDetails.RowCount = 2;
        pnlDetails.Padding = new Padding(8);
        pnlDetails.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlDetails.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        pnlDetails.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        lblDetails.Name = "lblDetails";
        lblDetails.Text = "Seçili işlemin kayıt ayrıntıları";
        lblDetails.Dock = DockStyle.Fill;
        lblDetails.BackColor = Color.FromArgb(218, 236, 250);
        lblDetails.TextAlign = ContentAlignment.MiddleLeft;
        detailGrid.Name = "detailGrid";
        detailGrid.Dock = DockStyle.Fill;
        detailGrid.ReadOnly = true;
        detailGrid.AllowUserToAddRows = false;
        detailGrid.AllowUserToDeleteRows = false;
        detailGrid.MultiSelect = false;
        detailGrid.BackgroundColor = Color.FromArgb(239, 247, 253);
        detailGrid.BorderStyle = BorderStyle.None;
        pnlDetails.Controls.Add(lblDetails, 0, 0);
        pnlDetails.Controls.Add(detailGrid, 0, 1);
        pnlRoot.Controls.Add(pnlDetails, 0, 3);
        Controls.Add(pnlRoot);
        btnRefresh.Click += Refresh_Click;
        btnClose.Click += Close_Click;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.FromArgb(228, 241, 252);
        ClientSize = new Size(1120, 760);
        MinimumSize = new Size(720, 520);
        StartPosition = FormStartPosition.CenterParent;
        KeyPreview = true;
        Name = "DataListForm";
        Text = "İşlem Geçmişi";
        ((System.ComponentModel.ISupportInitialize)grid).EndInit();
        pnlCommandBar.ResumeLayout(false);
        pnlCommandBar.PerformLayout();
        pnlHeader.ResumeLayout(false);
        pnlHeader.PerformLayout();
        pnlRoot.ResumeLayout(false);
        pnlRoot.PerformLayout();
        pnlListToolbar.ResumeLayout(false);
        pnlListToolbar.PerformLayout();
        pnlList.ResumeLayout(false);
        pnlList.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }
    #endregion
}
