using System;
using System.Drawing;
using System.Windows.Forms;

namespace BKS;

partial class PaymentDetailsForm
{
    private System.ComponentModel.IContainer components = null;

    private TextBox txtAmount;
    private DateTimePicker dtPayment;
    private TableLayoutPanel pnlEditor;
    private Label lbl_txtAmount;
    private Label lbl_dtPayment;
    private DataGridView paymentGrid;
    private TableLayoutPanel pnlPayments;
    private TableLayoutPanel pnlPaymentsToolbar;
    private Label pnlPaymentsTitle;
    private TextBox txtSearch;
    private Button pnlPaymentsClear;
    private Button pnlPaymentsColumns;
    private Label pnlPaymentsCount;
    private TableLayoutPanel pnlBody;
    private TableLayoutPanel pnlRoot;
    private TableLayoutPanel pnlHeader;
    private Label lblTitle;
    private Label lblSubtitle;
    private FlowLayoutPanel pnlCommandBar;
    private Button btnAdd;
    private Button btnApprove;
    private Button btnPlan;
    private Button btnRefresh;
    private Button btnClose;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        txtAmount = new TextBox();
        dtPayment = new DateTimePicker();
        pnlEditor = new TableLayoutPanel();
        lbl_txtAmount = new Label();
        lbl_dtPayment = new Label();
        paymentGrid = new DataGridView();
        pnlPayments = new TableLayoutPanel();
        pnlPaymentsToolbar = new TableLayoutPanel();
        pnlPaymentsTitle = new Label();
        txtSearch = new TextBox();
        pnlPaymentsClear = new Button();
        pnlPaymentsColumns = new Button();
        pnlPaymentsCount = new Label();
        pnlBody = new TableLayoutPanel();
        pnlRoot = new TableLayoutPanel();
        pnlHeader = new TableLayoutPanel();
        lblTitle = new Label();
        lblSubtitle = new Label();
        pnlCommandBar = new FlowLayoutPanel();
        btnAdd = new Button();
        btnApprove = new Button();
        btnPlan = new Button();
        btnRefresh = new Button();
        btnClose = new Button();
        ((System.ComponentModel.ISupportInitialize)paymentGrid).BeginInit();
        SuspendLayout();
        pnlEditor.SuspendLayout();
        pnlPayments.SuspendLayout();
        pnlPaymentsToolbar.SuspendLayout();
        pnlBody.SuspendLayout();
        pnlRoot.SuspendLayout();
        pnlHeader.SuspendLayout();
        pnlCommandBar.SuspendLayout();
        txtAmount.Name = "txtAmount";
        txtAmount.Dock = DockStyle.Fill;
        txtAmount.Margin = new Padding(0, 0, 16, 10);
        txtAmount.Size = new Size(260, 32);
        txtAmount.TabIndex = 1;
        txtAmount.Font = new Font("Segoe UI", 10F);
        txtAmount.ForeColor = Color.FromArgb(37, 54, 75);
        txtAmount.BorderStyle = BorderStyle.FixedSingle;
        dtPayment.Name = "dtPayment";
        dtPayment.Dock = DockStyle.Fill;
        dtPayment.Margin = new Padding(0, 0, 16, 10);
        dtPayment.Size = new Size(260, 32);
        dtPayment.TabIndex = 2;
        dtPayment.Font = new Font("Segoe UI", 10F);
        dtPayment.ForeColor = Color.FromArgb(37, 54, 75);
        dtPayment.Format = DateTimePickerFormat.Custom;
        dtPayment.CustomFormat = "dd.MM.yyyy";
        pnlEditor.Name = "pnlEditor";
        pnlEditor.Dock = DockStyle.Fill;
        pnlEditor.ColumnCount = 2;
        pnlEditor.RowCount = 3;
        pnlEditor.Margin = Padding.Empty;
        pnlEditor.Padding = new Padding(16);
        pnlEditor.BackColor = Color.FromArgb(239, 247, 253);
        pnlEditor.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        pnlEditor.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        pnlEditor.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        pnlEditor.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        pnlEditor.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlEditor.AutoScroll = true;
        lbl_txtAmount.Name = "lbl_txtAmount";
        lbl_txtAmount.AutoSize = true;
        lbl_txtAmount.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtAmount.Margin = new Padding(0, 2, 12, 6);
        lbl_txtAmount.Text = "Ödeme tutarı";
        lbl_dtPayment.Name = "lbl_dtPayment";
        lbl_dtPayment.AutoSize = true;
        lbl_dtPayment.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_dtPayment.Margin = new Padding(0, 2, 12, 6);
        lbl_dtPayment.Text = "Vade tarihi";
        paymentGrid.Name = "paymentGrid";
        paymentGrid.Dock = DockStyle.Fill;
        paymentGrid.BackgroundColor = Color.FromArgb(239, 247, 253);
        paymentGrid.BorderStyle = BorderStyle.None;
        paymentGrid.EnableHeadersVisualStyles = false;
        paymentGrid.ColumnHeadersHeight = 36;
        paymentGrid.RowHeadersWidth = 44;
        paymentGrid.AllowUserToAddRows = false;
        paymentGrid.AllowUserToDeleteRows = false;
        paymentGrid.ReadOnly = true;
        paymentGrid.AllowUserToOrderColumns = true;
        paymentGrid.AllowUserToResizeRows = false;
        paymentGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        paymentGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        paymentGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(218, 236, 250);
        paymentGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI Semibold", 9.5F);
        paymentGrid.ColumnHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(218, 236, 250);
        paymentGrid.DefaultCellStyle.Font = new Font("Segoe UI", 9.5F);
        paymentGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(200, 224, 246);
        paymentGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(37, 54, 75);
        paymentGrid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(239, 247, 253);
        paymentGrid.RowTemplate.Height = 32;
        pnlPayments.Name = "pnlPayments";
        pnlPayments.Dock = DockStyle.Fill;
        pnlPayments.ColumnCount = 1;
        pnlPayments.RowCount = 3;
        pnlPayments.Margin = Padding.Empty;
        pnlPayments.BackColor = Color.FromArgb(239, 247, 253);
        pnlPayments.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlPayments.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlPayments.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlPayments.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        pnlPayments.Padding = new Padding(8);
        pnlPaymentsToolbar.Name = "pnlPaymentsToolbar";
        pnlPaymentsToolbar.ColumnCount = 4;
        pnlPaymentsToolbar.RowCount = 1;
        pnlPaymentsToolbar.Margin = Padding.Empty;
        pnlPaymentsToolbar.BackColor = Color.FromArgb(218, 236, 250);
        pnlPaymentsToolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlPaymentsToolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 230F));
        pnlPaymentsToolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 112F));
        pnlPaymentsToolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 112F));
        pnlPaymentsToolbar.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        pnlPaymentsToolbar.Padding = Padding.Empty;
        pnlPaymentsToolbar.AutoSize = true;
        pnlPaymentsToolbar.Dock = DockStyle.Top;
        pnlPaymentsTitle.Name = "pnlPaymentsTitle";
        pnlPaymentsTitle.ForeColor = Color.FromArgb(68, 87, 111);
        pnlPaymentsTitle.Margin = new Padding(0, 2, 12, 6);
        pnlPaymentsTitle.Text = "Ödemeler";
        pnlPaymentsTitle.Font = new Font("Segoe UI Semibold", 11F);
        pnlPaymentsTitle.Anchor = AnchorStyles.Left;
        pnlPaymentsTitle.AutoEllipsis = true;
        pnlPaymentsTitle.AutoSize = false;
        pnlPaymentsTitle.Dock = DockStyle.Fill;
        txtSearch.Name = "txtSearch";
        txtSearch.Dock = DockStyle.Fill;
        txtSearch.Size = new Size(260, 32);
        txtSearch.TabIndex = 10;
        txtSearch.Font = new Font("Segoe UI", 10F);
        txtSearch.ForeColor = Color.FromArgb(37, 54, 75);
        txtSearch.BorderStyle = BorderStyle.FixedSingle;
        txtSearch.PlaceholderText = "Listede ara (Ctrl+F)";
        txtSearch.Margin = new Padding(0, 4, 8, 6);
        pnlPaymentsClear.Name = "pnlPaymentsClear";
        pnlPaymentsClear.AutoSize = true;
        pnlPaymentsClear.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlPaymentsClear.MinimumSize = new Size(96, 34);
        pnlPaymentsClear.Padding = new Padding(12, 4, 12, 4);
        pnlPaymentsClear.Margin = new Padding(0, 0, 8, 0);
        pnlPaymentsClear.FlatStyle = FlatStyle.Flat;
        pnlPaymentsClear.BackColor = Color.FromArgb(246, 248, 251);
        pnlPaymentsClear.ForeColor = Color.FromArgb(37, 54, 75);
        pnlPaymentsClear.UseVisualStyleBackColor = false;
        pnlPaymentsClear.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        pnlPaymentsClear.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        pnlPaymentsClear.Text = "Temizle";
        pnlPaymentsColumns.Name = "pnlPaymentsColumns";
        pnlPaymentsColumns.AutoSize = true;
        pnlPaymentsColumns.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlPaymentsColumns.MinimumSize = new Size(96, 34);
        pnlPaymentsColumns.Padding = new Padding(12, 4, 12, 4);
        pnlPaymentsColumns.Margin = new Padding(0, 0, 8, 0);
        pnlPaymentsColumns.FlatStyle = FlatStyle.Flat;
        pnlPaymentsColumns.BackColor = Color.FromArgb(246, 248, 251);
        pnlPaymentsColumns.ForeColor = Color.FromArgb(37, 54, 75);
        pnlPaymentsColumns.UseVisualStyleBackColor = false;
        pnlPaymentsColumns.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        pnlPaymentsColumns.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        pnlPaymentsColumns.Text = "Sütunlar";
        pnlPaymentsCount.Name = "pnlPaymentsCount";
        pnlPaymentsCount.AutoSize = true;
        pnlPaymentsCount.ForeColor = Color.FromArgb(68, 87, 111);
        pnlPaymentsCount.Margin = new Padding(0, 2, 12, 6);
        pnlPaymentsCount.Text = "Kayıt: 0";
        pnlPaymentsCount.Dock = DockStyle.Fill;
        pnlBody.Name = "pnlBody";
        pnlBody.Dock = DockStyle.Fill;
        pnlBody.ColumnCount = 1;
        pnlBody.RowCount = 2;
        pnlBody.Margin = Padding.Empty;
        pnlBody.BackColor = Color.FromArgb(239, 247, 253);
        pnlBody.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 108F));
        pnlBody.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlBody.Padding = Padding.Empty;
        pnlRoot.Name = "pnlRoot";
        pnlRoot.Dock = DockStyle.Fill;
        pnlRoot.ColumnCount = 1;
        pnlRoot.RowCount = 3;
        pnlRoot.Margin = Padding.Empty;
        pnlRoot.BackColor = Color.FromArgb(228, 241, 252);
        pnlRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 78F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlRoot.Padding = Padding.Empty;
        pnlHeader.Name = "pnlHeader";
        pnlHeader.Dock = DockStyle.Fill;
        pnlHeader.ColumnCount = 1;
        pnlHeader.RowCount = 2;
        pnlHeader.Margin = Padding.Empty;
        pnlHeader.BackColor = Color.FromArgb(218, 236, 250);
        pnlHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlHeader.Padding = new Padding(16, 6, 16, 0);
        lblTitle.Name = "lblTitle";
        lblTitle.ForeColor = Color.FromArgb(68, 87, 111);
        lblTitle.Margin = new Padding(0, 2, 12, 6);
        lblTitle.Text = "Öğrenci Ödeme Detayları";
        lblTitle.Font = new Font("Segoe UI Semibold", 15F);
        lblTitle.AutoSize = true;
        lblSubtitle.Name = "lblSubtitle";
        lblSubtitle.ForeColor = Color.FromArgb(68, 87, 111);
        lblSubtitle.Margin = new Padding(0, 2, 12, 6);
        lblSubtitle.Text = "Aylık / yıllık plan oluşturun; tahsil edilen ödemeleri seçip onaylayın.";
        lblSubtitle.AutoSize = true;
        pnlCommandBar.Name = "pnlCommandBar";
        pnlCommandBar.Dock = DockStyle.Top;
        pnlCommandBar.AutoSize = true;
        pnlCommandBar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlCommandBar.WrapContents = true;
        pnlCommandBar.Padding = new Padding(16, 8, 8, 8);
        pnlCommandBar.Margin = Padding.Empty;
        pnlCommandBar.BackColor = Color.FromArgb(228, 241, 252);
        btnAdd.Name = "btnAdd";
        btnAdd.AutoSize = true;
        btnAdd.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnAdd.MinimumSize = new Size(96, 34);
        btnAdd.Padding = new Padding(12, 4, 12, 4);
        btnAdd.Margin = new Padding(0, 0, 8, 0);
        btnAdd.FlatStyle = FlatStyle.Flat;
        btnAdd.BackColor = Color.FromArgb(40, 99, 163);
        btnAdd.ForeColor = Color.White;
        btnAdd.UseVisualStyleBackColor = false;
        btnAdd.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        btnAdd.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnAdd.Text = "Tek ödeme ekle";
        btnApprove.Name = "btnApprove";
        btnApprove.AutoSize = true;
        btnApprove.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnApprove.MinimumSize = new Size(96, 34);
        btnApprove.Padding = new Padding(12, 4, 12, 4);
        btnApprove.Margin = new Padding(0, 0, 8, 0);
        btnApprove.FlatStyle = FlatStyle.Flat;
        btnApprove.BackColor = Color.FromArgb(246, 248, 251);
        btnApprove.ForeColor = Color.FromArgb(37, 54, 75);
        btnApprove.UseVisualStyleBackColor = false;
        btnApprove.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        btnApprove.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnApprove.Text = "Seçilenleri onayla";
        btnPlan.Name = "btnPlan";
        btnPlan.AutoSize = true;
        btnPlan.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnPlan.MinimumSize = new Size(96, 34);
        btnPlan.Padding = new Padding(12, 4, 12, 4);
        btnPlan.Margin = new Padding(0, 0, 8, 0);
        btnPlan.FlatStyle = FlatStyle.Flat;
        btnPlan.BackColor = Color.FromArgb(246, 248, 251);
        btnPlan.ForeColor = Color.FromArgb(37, 54, 75);
        btnPlan.UseVisualStyleBackColor = false;
        btnPlan.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        btnPlan.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnPlan.Text = "Aylık / yıllık plan";
        btnRefresh.Name = "btnRefresh";
        btnRefresh.AutoSize = true;
        btnRefresh.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnRefresh.MinimumSize = new Size(96, 34);
        btnRefresh.Padding = new Padding(12, 4, 12, 4);
        btnRefresh.Margin = new Padding(0, 0, 8, 0);
        btnRefresh.FlatStyle = FlatStyle.Flat;
        btnRefresh.BackColor = Color.FromArgb(246, 248, 251);
        btnRefresh.ForeColor = Color.FromArgb(37, 54, 75);
        btnRefresh.UseVisualStyleBackColor = false;
        btnRefresh.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        btnRefresh.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnRefresh.Text = "Yenile";
        btnClose.Name = "btnClose";
        btnClose.AutoSize = true;
        btnClose.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnClose.MinimumSize = new Size(96, 34);
        btnClose.Padding = new Padding(12, 4, 12, 4);
        btnClose.Margin = new Padding(0, 0, 8, 0);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.BackColor = Color.FromArgb(246, 248, 251);
        btnClose.ForeColor = Color.FromArgb(37, 54, 75);
        btnClose.UseVisualStyleBackColor = false;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(189, 214, 235);
        btnClose.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnClose.Text = "Kapat";
        paymentGrid.MultiSelect = true;
        pnlEditor.Controls.Add(lbl_txtAmount, 0, 0);
        pnlEditor.Controls.Add(txtAmount, 0, 1);
        pnlEditor.Controls.Add(lbl_dtPayment, 1, 0);
        pnlEditor.Controls.Add(dtPayment, 1, 1);
        pnlPaymentsToolbar.Controls.Add(pnlPaymentsTitle, 0, 0);
        pnlPaymentsToolbar.Controls.Add(txtSearch, 1, 0);
        pnlPaymentsToolbar.Controls.Add(pnlPaymentsClear, 2, 0);
        pnlPaymentsToolbar.Controls.Add(pnlPaymentsColumns, 3, 0);
        pnlPayments.Controls.Add(pnlPaymentsToolbar, 0, 0);
        pnlPayments.Controls.Add(paymentGrid, 0, 1);
        pnlPayments.Controls.Add(pnlPaymentsCount, 0, 2);
        pnlBody.Controls.Add(pnlEditor, 0, 0);
        pnlBody.Controls.Add(pnlPayments, 0, 1);
        pnlHeader.Controls.Add(lblTitle, 0, 0);
        pnlHeader.Controls.Add(lblSubtitle, 0, 1);
        pnlRoot.Controls.Add(pnlHeader, 0, 0);
        pnlCommandBar.Controls.Add(btnAdd);
        pnlCommandBar.Controls.Add(btnApprove);
        pnlCommandBar.Controls.Add(btnPlan);
        pnlCommandBar.Controls.Add(btnRefresh);
        pnlCommandBar.Controls.Add(btnClose);
        pnlRoot.Controls.Add(pnlCommandBar, 0, 1);
        pnlRoot.Controls.Add(pnlBody, 0, 2);
        Controls.Add(pnlRoot);
        btnAdd.Click += Add_Click;
        btnApprove.Click += Approve_Click;
        btnPlan.Click += Plan_Click;
        btnRefresh.Click += Refresh_Click;
        btnClose.Click += Close_Click;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.FromArgb(228, 241, 252);
        ClientSize = new Size(1120, 760);
        MinimumSize = new Size(720, 520);
        StartPosition = FormStartPosition.CenterParent;
        KeyPreview = true;
        Name = "PaymentDetailsForm";
        Text = "Öğrenci Ödeme Detayları";
        ((System.ComponentModel.ISupportInitialize)paymentGrid).EndInit();
        pnlCommandBar.ResumeLayout(false);
        pnlCommandBar.PerformLayout();
        pnlHeader.ResumeLayout(false);
        pnlHeader.PerformLayout();
        pnlRoot.ResumeLayout(false);
        pnlRoot.PerformLayout();
        pnlBody.ResumeLayout(false);
        pnlBody.PerformLayout();
        pnlPaymentsToolbar.ResumeLayout(false);
        pnlPaymentsToolbar.PerformLayout();
        pnlPayments.ResumeLayout(false);
        pnlPayments.PerformLayout();
        pnlEditor.ResumeLayout(false);
        pnlEditor.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }
    #endregion
}
