using System;
using System.Drawing;
using System.Windows.Forms;

namespace BKS;

partial class PaymentPlanForm
{
    private System.ComponentModel.IContainer components = null;

    private TextBox txtAmount;
    private NumericUpDown nudMonths;
    private TableLayoutPanel pnlEditor;
    private Label lbl_txtAmount;
    private Label lbl_nudMonths;
    private TableLayoutPanel pnlRoot;
    private TableLayoutPanel pnlHeader;
    private Label lblTitle;
    private Label lblSubtitle;
    private FlowLayoutPanel pnlCommandBar;
    private Button btnCreate;
    private Button btnClose;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        txtAmount = new TextBox();
        nudMonths = new NumericUpDown();
        pnlEditor = new TableLayoutPanel();
        lbl_txtAmount = new Label();
        lbl_nudMonths = new Label();
        pnlRoot = new TableLayoutPanel();
        pnlHeader = new TableLayoutPanel();
        lblTitle = new Label();
        lblSubtitle = new Label();
        pnlCommandBar = new FlowLayoutPanel();
        btnCreate = new Button();
        btnClose = new Button();
        ((System.ComponentModel.ISupportInitialize)nudMonths).BeginInit();
        SuspendLayout();
        pnlEditor.SuspendLayout();
        pnlRoot.SuspendLayout();
        pnlHeader.SuspendLayout();
        pnlCommandBar.SuspendLayout();
        txtAmount.Name = "txtAmount";
        txtAmount.Dock = DockStyle.Fill;
        txtAmount.Margin = new Padding(0, 0, 16, 10);
        txtAmount.Size = new Size(260, 32);
        txtAmount.TabIndex = 1;
        txtAmount.Font = new Font("Segoe UI", 10F);
        txtAmount.ForeColor = Color.FromArgb(37, 54, 75);
        txtAmount.BorderStyle = BorderStyle.FixedSingle;
        nudMonths.Name = "nudMonths";
        nudMonths.Dock = DockStyle.Fill;
        nudMonths.Margin = new Padding(0, 0, 16, 10);
        nudMonths.Size = new Size(260, 32);
        nudMonths.TabIndex = 2;
        nudMonths.Font = new Font("Segoe UI", 10F);
        nudMonths.ForeColor = Color.FromArgb(37, 54, 75);
        nudMonths.ThousandsSeparator = true;
        nudMonths.TextAlign = HorizontalAlignment.Right;
        nudMonths.Minimum = 1M;
        nudMonths.Maximum = 24M;
        nudMonths.Value = 1M;
        pnlEditor.Name = "pnlEditor";
        pnlEditor.Dock = DockStyle.Fill;
        pnlEditor.ColumnCount = 2;
        pnlEditor.RowCount = 3;
        pnlEditor.Margin = Padding.Empty;
        pnlEditor.Padding = new Padding(16);
        pnlEditor.BackColor = Color.White;
        pnlEditor.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        pnlEditor.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        pnlEditor.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        pnlEditor.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        pnlEditor.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlEditor.AutoScroll = true;
        lbl_txtAmount.Name = "lbl_txtAmount";
        lbl_txtAmount.AutoSize = true;
        lbl_txtAmount.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtAmount.Margin = new Padding(0, 2, 12, 6);
        lbl_txtAmount.Text = "Aylık tutar";
        lbl_nudMonths.Name = "lbl_nudMonths";
        lbl_nudMonths.AutoSize = true;
        lbl_nudMonths.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_nudMonths.Margin = new Padding(0, 2, 12, 6);
        lbl_nudMonths.Text = "Ay sayısı";
        pnlRoot.Name = "pnlRoot";
        pnlRoot.Dock = DockStyle.Fill;
        pnlRoot.ColumnCount = 1;
        pnlRoot.RowCount = 3;
        pnlRoot.Margin = Padding.Empty;
        pnlRoot.BackColor = Color.White;
        pnlRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 62F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlRoot.Padding = Padding.Empty;
        pnlHeader.Name = "pnlHeader";
        pnlHeader.Dock = DockStyle.Fill;
        pnlHeader.ColumnCount = 1;
        pnlHeader.RowCount = 2;
        pnlHeader.Margin = Padding.Empty;
        pnlHeader.BackColor = Color.White;
        pnlHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlHeader.Padding = new Padding(16, 6, 16, 0);
        lblTitle.Name = "lblTitle";
        lblTitle.ForeColor = Color.FromArgb(68, 87, 111);
        lblTitle.Margin = new Padding(0, 2, 12, 6);
        lblTitle.Text = "Aylık Ödeme Planı";
        lblTitle.Font = new Font("Segoe UI Semibold", 15F);
        lblTitle.AutoSize = true;
        lblSubtitle.Name = "lblSubtitle";
        lblSubtitle.ForeColor = Color.FromArgb(68, 87, 111);
        lblSubtitle.Margin = new Padding(0, 2, 12, 6);
        lblSubtitle.Text = "Bilgileri düzenleyin; değişikliklerinizi kaydedin.";
        lblSubtitle.AutoSize = true;
        pnlCommandBar.Name = "pnlCommandBar";
        pnlCommandBar.Dock = DockStyle.Top;
        pnlCommandBar.AutoSize = true;
        pnlCommandBar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlCommandBar.WrapContents = true;
        pnlCommandBar.Padding = new Padding(16, 8, 8, 8);
        pnlCommandBar.Margin = Padding.Empty;
        pnlCommandBar.BackColor = Color.White;
        btnCreate.Name = "btnCreate";
        btnCreate.AutoSize = true;
        btnCreate.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnCreate.MinimumSize = new Size(96, 34);
        btnCreate.Padding = new Padding(12, 4, 12, 4);
        btnCreate.Margin = new Padding(0, 0, 8, 0);
        btnCreate.FlatStyle = FlatStyle.Flat;
        btnCreate.BackColor = Color.FromArgb(40, 99, 163);
        btnCreate.ForeColor = Color.White;
        btnCreate.UseVisualStyleBackColor = false;
        btnCreate.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnCreate.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnCreate.Text = "Plan oluştur";
        btnClose.Name = "btnClose";
        btnClose.AutoSize = true;
        btnClose.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnClose.MinimumSize = new Size(96, 34);
        btnClose.Padding = new Padding(12, 4, 12, 4);
        btnClose.Margin = new Padding(0, 0, 8, 0);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.BackColor = Color.FromArgb(246, 248, 251);
        btnClose.ForeColor = Color.FromArgb(37, 54, 75);
        btnClose.UseVisualStyleBackColor = false;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnClose.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnClose.Text = "Kapat";
        pnlEditor.Controls.Add(lbl_txtAmount, 0, 0);
        pnlEditor.Controls.Add(txtAmount, 0, 1);
        pnlEditor.Controls.Add(lbl_nudMonths, 1, 0);
        pnlEditor.Controls.Add(nudMonths, 1, 1);
        pnlHeader.Controls.Add(lblTitle, 0, 0);
        pnlHeader.Controls.Add(lblSubtitle, 0, 1);
        pnlRoot.Controls.Add(pnlHeader, 0, 0);
        pnlCommandBar.Controls.Add(btnCreate);
        pnlCommandBar.Controls.Add(btnClose);
        pnlRoot.Controls.Add(pnlCommandBar, 0, 1);
        pnlRoot.Controls.Add(pnlEditor, 0, 2);
        Controls.Add(pnlRoot);
        btnCreate.Click += Create_Click;
        btnClose.Click += Close_Click;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.White;
        ClientSize = new Size(1120, 760);
        MinimumSize = new Size(720, 520);
        StartPosition = FormStartPosition.CenterParent;
        KeyPreview = true;
        Name = "PaymentPlanForm";
        Text = "Aylık Ödeme Planı";
        ((System.ComponentModel.ISupportInitialize)nudMonths).EndInit();
        pnlCommandBar.ResumeLayout(false);
        pnlCommandBar.PerformLayout();
        pnlHeader.ResumeLayout(false);
        pnlHeader.PerformLayout();
        pnlRoot.ResumeLayout(false);
        pnlRoot.PerformLayout();
        pnlEditor.ResumeLayout(false);
        pnlEditor.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }
    #endregion
}
