using System;
using System.Drawing;
using System.Windows.Forms;
namespace BKS;
partial class PaymentPlanForm
{
    private System.ComponentModel.IContainer components;
    private TableLayoutPanel pnlRoot;
    private TableLayoutPanel pnlEditor;
    private Label lblTitle;
    private Label lblFrequency;
    private Label lblPeriods;
    private Label lblStart;
    private Label lblAmount;
    private Label lblTotal;
    private ComboBox cmbFrequency;
    private NumericUpDown nudPeriods;
    private NumericUpDown nudAmount;
    private DateTimePicker dtStart;
    private DataGridView gridPreview;
    private FlowLayoutPanel pnlCommands;
    private Button btnCreate;
    private Button btnClose;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        pnlRoot = new TableLayoutPanel();
        pnlEditor = new TableLayoutPanel();
        lblTitle = new Label();
        lblFrequency = new Label();
        lblPeriods = new Label();
        lblStart = new Label();
        lblAmount = new Label();
        lblTotal = new Label();
        cmbFrequency = new ComboBox();
        nudPeriods = new NumericUpDown();
        nudAmount = new NumericUpDown();
        dtStart = new DateTimePicker();
        gridPreview = new DataGridView();
        pnlCommands = new FlowLayoutPanel();
        btnCreate = new Button();
        btnClose = new Button();
        ((System.ComponentModel.ISupportInitialize)nudPeriods).BeginInit();
        ((System.ComponentModel.ISupportInitialize)nudAmount).BeginInit();
        ((System.ComponentModel.ISupportInitialize)gridPreview).BeginInit();
        SuspendLayout();
        pnlRoot.SuspendLayout();
        pnlEditor.SuspendLayout();
        pnlCommands.SuspendLayout();
        pnlRoot.Name = "pnlRoot";
        pnlRoot.Dock = DockStyle.Fill;
        pnlRoot.BackColor = Color.FromArgb(228, 241, 252);
        pnlRoot.Padding = new Padding(16);
        pnlRoot.ColumnCount = 1;
        pnlRoot.RowCount = 5;
        pnlRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 142F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        lblTitle.Text = "Aylık / yıllık ödeme planı";
        lblTitle.Font = new Font("Segoe UI Semibold", 16F);
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.AutoEllipsis = true;
        pnlEditor.Name = "pnlEditor";
        pnlEditor.Dock = DockStyle.Fill;
        pnlEditor.ColumnCount = 2;
        pnlEditor.RowCount = 4;
        pnlEditor.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        pnlEditor.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        pnlEditor.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        pnlEditor.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        pnlEditor.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        pnlEditor.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        lblFrequency.Text = "Ödeme dönemi";
        lblPeriods.Text = "Dönem sayısı";
        lblStart.Text = "İlk vade tarihi";
        lblAmount.Text = "Her dönem için tutar (TL)";
        lblFrequency.AutoSize = true;
        lblPeriods.AutoSize = true;
        lblStart.AutoSize = true;
        lblAmount.AutoSize = true;
        cmbFrequency.Name = "cmbFrequency";
        cmbFrequency.Dock = DockStyle.Fill;
        cmbFrequency.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbFrequency.Items.AddRange(new object[] { "Aylık", "Yıllık" });
        nudPeriods.Name = "nudPeriods";
        nudPeriods.Dock = DockStyle.Fill;
        nudPeriods.Minimum = 1;
        nudPeriods.Maximum = 120;
        nudPeriods.Value = 12;
        nudAmount.Name = "nudAmount";
        nudAmount.Dock = DockStyle.Fill;
        nudAmount.DecimalPlaces = 2;
        nudAmount.Maximum = 999999999;
        nudAmount.ThousandsSeparator = true;
        dtStart.Name = "dtStart";
        dtStart.Dock = DockStyle.Fill;
        dtStart.Format = DateTimePickerFormat.Custom;
        dtStart.CustomFormat = "dd.MM.yyyy";
        gridPreview.Name = "gridPreview";
        gridPreview.Dock = DockStyle.Fill;
        gridPreview.ReadOnly = true;
        gridPreview.AllowUserToAddRows = false;
        gridPreview.AllowUserToDeleteRows = false;
        gridPreview.MultiSelect = false;
        gridPreview.BackgroundColor = Color.FromArgb(239, 247, 253);
        gridPreview.BorderStyle = BorderStyle.None;
        lblTotal.Name = "lblTotal";
        lblTotal.Dock = DockStyle.Fill;
        lblTotal.TextAlign = ContentAlignment.MiddleLeft;
        lblTotal.AutoEllipsis = true;
        lblTotal.Text = "Tutarı girerek planı önizleyin.";
        pnlCommands.Name = "pnlCommands";
        pnlCommands.Dock = DockStyle.Fill;
        pnlCommands.AutoSize = true;
        pnlCommands.WrapContents = true;
        btnCreate.Name = "btnCreate";
        btnCreate.Text = "Planı kaydet";
        btnCreate.AutoSize = true;
        btnCreate.Padding = new Padding(12, 6, 12, 6);
        btnCreate.FlatStyle = FlatStyle.Flat;
        btnCreate.BackColor = Color.FromArgb(40, 99, 163);
        btnCreate.ForeColor = Color.White;
        btnClose.Name = "btnClose";
        btnClose.Text = "Vazgeç";
        btnClose.AutoSize = true;
        btnClose.Padding = new Padding(12, 6, 12, 6);
        pnlEditor.Controls.Add(lblFrequency, 0, 0);
        pnlEditor.Controls.Add(cmbFrequency, 0, 1);
        pnlEditor.Controls.Add(lblPeriods, 1, 0);
        pnlEditor.Controls.Add(nudPeriods, 1, 1);
        pnlEditor.Controls.Add(lblStart, 0, 2);
        pnlEditor.Controls.Add(dtStart, 0, 3);
        pnlEditor.Controls.Add(lblAmount, 1, 2);
        pnlEditor.Controls.Add(nudAmount, 1, 3);
        pnlCommands.Controls.Add(btnCreate);
        pnlCommands.Controls.Add(btnClose);
        pnlRoot.Controls.Add(lblTitle, 0, 0);
        pnlRoot.Controls.Add(pnlEditor, 0, 1);
        pnlRoot.Controls.Add(gridPreview, 0, 2);
        pnlRoot.Controls.Add(lblTotal, 0, 3);
        pnlRoot.Controls.Add(pnlCommands, 0, 4);
        Controls.Add(pnlRoot);
        cmbFrequency.SelectedIndexChanged += FrequencyChanged;
        nudPeriods.ValueChanged += PlanChanged;
        nudAmount.ValueChanged += PlanChanged;
        dtStart.ValueChanged += PlanChanged;
        btnCreate.Click += Create_Click;
        btnClose.Click += Close_Click;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.FromArgb(228, 241, 252);
        ForeColor = Color.FromArgb(37, 54, 75);
        ClientSize = new Size(900, 660);
        MinimumSize = new Size(600, 440);
        StartPosition = FormStartPosition.CenterParent;
        Text = "Ödeme planı";
        Name = "PaymentPlanForm";
        ((System.ComponentModel.ISupportInitialize)nudPeriods).EndInit();
        ((System.ComponentModel.ISupportInitialize)nudAmount).EndInit();
        ((System.ComponentModel.ISupportInitialize)gridPreview).EndInit();
        pnlCommands.ResumeLayout(false);
        pnlCommands.PerformLayout();
        pnlEditor.ResumeLayout(false);
        pnlEditor.PerformLayout();
        pnlRoot.ResumeLayout(false);
        pnlRoot.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }
}
