using System;
using System.Drawing;
using System.Windows.Forms;

namespace BKS;

partial class PersonelForm
{
    private System.ComponentModel.IContainer components = null;

    public FlowLayoutPanel panel1;
    public RadioButton rbtPersonelErkek;
    public RadioButton rbtPersonelKadin;
    public FlowLayoutPanel panel2;
    public RadioButton rbtPersonelEvli;
    public RadioButton rbtPersonelBekar;
    public FlowLayoutPanel panel3;
    public RadioButton rbtPersonelEgitimGorevlisiEvet;
    public RadioButton rbtPersonelEgitimGorevlisiHayir;
    private TableLayoutPanel tlpIdentity;
    public TextBox txtPersonelAd;
    private Label lbl_txtPersonelAd;
    public TextBox txtPersonelSoyad;
    private Label lbl_txtPersonelSoyad;
    public ComboBox cbxPersonelUyruk;
    private Label lbl_cbxPersonelUyruk;
    public TextBox txtPersonelKimlik;
    public Label lblKimlikNum;
    public DateTimePicker dtpPersonelDG;
    private Label lbl_dtpPersonelDG;
    private Label lbl_panel1;
    private Label lbl_panel2;
    private TableLayoutPanel pnlPhoto;
    public PictureBox pbxPersonelPicture;
    private Button btnChoosePhoto;
    private Button btnRemovePhoto;
    private Label lblPhotoStatus;
    private TableLayoutPanel pnlIdentity;
    private TableLayoutPanel tlpContact;
    public TextBox txtPersonelTel;
    private Label lbl_txtPersonelTel;
    public TextBox txtPersonelMail;
    private Label lbl_txtPersonelMail;
    public TextBox txtPersonelAdres;
    private Label lbl_txtPersonelAdres;
    public TextBox txtPersonelIletişimAcilDurum;
    private Label lbl_txtPersonelIletişimAcilDurum;
    private TableLayoutPanel tlpWork;
    public DateTimePicker dtpPersonelIseBaslamaTarihi;
    private Label lbl_dtpPersonelIseBaslamaTarihi;
    public TextBox txtPersonelDepartman;
    private Label lbl_txtPersonelDepartman;
    public TextBox txtPersonelGorev;
    private Label lbl_txtPersonelGorev;
    public TextBox txtPersonelPersonelNo;
    private Label lbl_txtPersonelPersonelNo;
    public ComboBox cbxPersonelCalismaSekli;
    private Label lbl_cbxPersonelCalismaSekli;
    private Label lbl_panel3;
    private TableLayoutPanel tlpEducation;
    public ComboBox cbxPersonelEgitimDurumu;
    private Label lbl_cbxPersonelEgitimDurumu;
    public ComboBox cbxPersonelUniversite;
    private Label lbl_cbxPersonelUniversite;
    public TextBox txtPersonelUniBolum;
    private Label lbl_txtPersonelUniBolum;
    public TextBox txtPersonelYabanciDil;
    private Label lbl_txtPersonelYabanciDil;
    public TextBox txtPersonelSertifika;
    private Label lbl_txtPersonelSertifika;
    private TableLayoutPanel tlpSalary;
    public TextBox txtPersonelMaas;
    private Label lbl_txtPersonelMaas;
    public TextBox txtPersonelPrimVeEk;
    private Label lbl_txtPersonelPrimVeEk;
    public TextBox txtPersonelYemekYol;
    private Label lbl_txtPersonelYemekYol;
    public ComboBox cbxPersonelSigorta;
    private Label lbl_cbxPersonelSigorta;
    public TextBox txtPersonelSGKSicilNum;
    private Label lbl_txtPersonelSGKSicilNum;
    public TextBox txtPersonelSaglikSigorta;
    private Label lbl_txtPersonelSaglikSigorta;
    public TextBox txtPersonelEmeklilik;
    private Label lbl_txtPersonelEmeklilik;
    private TableLayoutPanel tlpLeave;
    public CheckBox cbxPersoneIIsAyrıldı;
    private Label lbl_cbxPersoneIIsAyrıldı;
    public DateTimePicker dtpPersonelCıkısTarihi;
    private Label lbl_dtpPersonelCıkısTarihi;
    public TextBox txtPersonelAyrilmaNedeni;
    private Label lbl_txtPersonelAyrilmaNedeni;
    public TextBox txtPersonelKidemTazminat;
    private Label lbl_txtPersonelKidemTazminat;
    private TabControl tabPersonnelDetails;
    private TabPage tabIdentity;
    private TabPage tabContact;
    private TabPage tabWork;
    private TabPage tabEducation;
    private TabPage tabSalary;
    private TabPage tabLeave;
    private TableLayoutPanel pnlRoot;
    private TableLayoutPanel pnlHeader;
    private Label lblTitle;
    private Label lblSubtitle;
    private FlowLayoutPanel pnlCommandBar;
    private Button btnPersonelKaydet;
    private Button btnPersonelGuncelle;
    private Button btnPersonelSil;
    private Button btnPersonelTemizle;
    private Button btnClose;

    protected override void Dispose(bool disposing)
    {
        if (disposing) DisposePhotoLoader();
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        panel1 = new FlowLayoutPanel();
        rbtPersonelErkek = new RadioButton();
        rbtPersonelKadin = new RadioButton();
        panel2 = new FlowLayoutPanel();
        rbtPersonelEvli = new RadioButton();
        rbtPersonelBekar = new RadioButton();
        panel3 = new FlowLayoutPanel();
        rbtPersonelEgitimGorevlisiEvet = new RadioButton();
        rbtPersonelEgitimGorevlisiHayir = new RadioButton();
        tlpIdentity = new TableLayoutPanel();
        txtPersonelAd = new TextBox();
        lbl_txtPersonelAd = new Label();
        txtPersonelSoyad = new TextBox();
        lbl_txtPersonelSoyad = new Label();
        cbxPersonelUyruk = new ComboBox();
        lbl_cbxPersonelUyruk = new Label();
        txtPersonelKimlik = new TextBox();
        lblKimlikNum = new Label();
        dtpPersonelDG = new DateTimePicker();
        lbl_dtpPersonelDG = new Label();
        lbl_panel1 = new Label();
        lbl_panel2 = new Label();
        pnlPhoto = new TableLayoutPanel();
        pbxPersonelPicture = new PictureBox();
        btnChoosePhoto = new Button();
        btnRemovePhoto = new Button();
        lblPhotoStatus = new Label();
        pnlIdentity = new TableLayoutPanel();
        tlpContact = new TableLayoutPanel();
        txtPersonelTel = new TextBox();
        lbl_txtPersonelTel = new Label();
        txtPersonelMail = new TextBox();
        lbl_txtPersonelMail = new Label();
        txtPersonelAdres = new TextBox();
        lbl_txtPersonelAdres = new Label();
        txtPersonelIletişimAcilDurum = new TextBox();
        lbl_txtPersonelIletişimAcilDurum = new Label();
        tlpWork = new TableLayoutPanel();
        dtpPersonelIseBaslamaTarihi = new DateTimePicker();
        lbl_dtpPersonelIseBaslamaTarihi = new Label();
        txtPersonelDepartman = new TextBox();
        lbl_txtPersonelDepartman = new Label();
        txtPersonelGorev = new TextBox();
        lbl_txtPersonelGorev = new Label();
        txtPersonelPersonelNo = new TextBox();
        lbl_txtPersonelPersonelNo = new Label();
        cbxPersonelCalismaSekli = new ComboBox();
        lbl_cbxPersonelCalismaSekli = new Label();
        lbl_panel3 = new Label();
        tlpEducation = new TableLayoutPanel();
        cbxPersonelEgitimDurumu = new ComboBox();
        lbl_cbxPersonelEgitimDurumu = new Label();
        cbxPersonelUniversite = new ComboBox();
        lbl_cbxPersonelUniversite = new Label();
        txtPersonelUniBolum = new TextBox();
        lbl_txtPersonelUniBolum = new Label();
        txtPersonelYabanciDil = new TextBox();
        lbl_txtPersonelYabanciDil = new Label();
        txtPersonelSertifika = new TextBox();
        lbl_txtPersonelSertifika = new Label();
        tlpSalary = new TableLayoutPanel();
        txtPersonelMaas = new TextBox();
        lbl_txtPersonelMaas = new Label();
        txtPersonelPrimVeEk = new TextBox();
        lbl_txtPersonelPrimVeEk = new Label();
        txtPersonelYemekYol = new TextBox();
        lbl_txtPersonelYemekYol = new Label();
        cbxPersonelSigorta = new ComboBox();
        lbl_cbxPersonelSigorta = new Label();
        txtPersonelSGKSicilNum = new TextBox();
        lbl_txtPersonelSGKSicilNum = new Label();
        txtPersonelSaglikSigorta = new TextBox();
        lbl_txtPersonelSaglikSigorta = new Label();
        txtPersonelEmeklilik = new TextBox();
        lbl_txtPersonelEmeklilik = new Label();
        tlpLeave = new TableLayoutPanel();
        cbxPersoneIIsAyrıldı = new CheckBox();
        lbl_cbxPersoneIIsAyrıldı = new Label();
        dtpPersonelCıkısTarihi = new DateTimePicker();
        lbl_dtpPersonelCıkısTarihi = new Label();
        txtPersonelAyrilmaNedeni = new TextBox();
        lbl_txtPersonelAyrilmaNedeni = new Label();
        txtPersonelKidemTazminat = new TextBox();
        lbl_txtPersonelKidemTazminat = new Label();
        tabPersonnelDetails = new TabControl();
        tabIdentity = new TabPage();
        tabContact = new TabPage();
        tabWork = new TabPage();
        tabEducation = new TabPage();
        tabSalary = new TabPage();
        tabLeave = new TabPage();
        pnlRoot = new TableLayoutPanel();
        pnlHeader = new TableLayoutPanel();
        lblTitle = new Label();
        lblSubtitle = new Label();
        pnlCommandBar = new FlowLayoutPanel();
        btnPersonelKaydet = new Button();
        btnPersonelGuncelle = new Button();
        btnPersonelSil = new Button();
        btnPersonelTemizle = new Button();
        btnClose = new Button();
        ((System.ComponentModel.ISupportInitialize)pbxPersonelPicture).BeginInit();
        SuspendLayout();
        panel1.SuspendLayout();
        panel2.SuspendLayout();
        panel3.SuspendLayout();
        tlpIdentity.SuspendLayout();
        pnlPhoto.SuspendLayout();
        pnlIdentity.SuspendLayout();
        tlpContact.SuspendLayout();
        tlpWork.SuspendLayout();
        tlpEducation.SuspendLayout();
        tlpSalary.SuspendLayout();
        tlpLeave.SuspendLayout();
        tabPersonnelDetails.SuspendLayout();
        tabIdentity.SuspendLayout();
        tabContact.SuspendLayout();
        tabWork.SuspendLayout();
        tabEducation.SuspendLayout();
        tabSalary.SuspendLayout();
        tabLeave.SuspendLayout();
        pnlRoot.SuspendLayout();
        pnlHeader.SuspendLayout();
        pnlCommandBar.SuspendLayout();
        panel1.Name = "panel1";
        panel1.Dock = DockStyle.Fill;
        panel1.WrapContents = true;
        panel1.Margin = Padding.Empty;
        rbtPersonelErkek.Text = "Erkek";
        rbtPersonelErkek.Name = "rbtPersonelErkek";
        rbtPersonelErkek.AutoSize = true;
        rbtPersonelErkek.Anchor = AnchorStyles.Left;
        rbtPersonelErkek.Margin = new Padding(0, 3, 16, 6);
        rbtPersonelKadin.Text = "Kadın";
        rbtPersonelKadin.Name = "rbtPersonelKadin";
        rbtPersonelKadin.AutoSize = true;
        rbtPersonelKadin.Anchor = AnchorStyles.Left;
        rbtPersonelKadin.Margin = new Padding(0, 3, 16, 6);
        panel2.Name = "panel2";
        panel2.Dock = DockStyle.Fill;
        panel2.WrapContents = true;
        panel2.Margin = Padding.Empty;
        rbtPersonelEvli.Text = "Evli";
        rbtPersonelEvli.Name = "rbtPersonelEvli";
        rbtPersonelEvli.AutoSize = true;
        rbtPersonelEvli.Anchor = AnchorStyles.Left;
        rbtPersonelEvli.Margin = new Padding(0, 3, 16, 6);
        rbtPersonelBekar.TabStop = true;
        rbtPersonelBekar.Text = "Bekar";
        rbtPersonelBekar.Name = "rbtPersonelBekar";
        rbtPersonelBekar.AutoSize = true;
        rbtPersonelBekar.Anchor = AnchorStyles.Left;
        rbtPersonelBekar.Margin = new Padding(0, 3, 16, 6);
        panel3.Name = "panel3";
        panel3.Dock = DockStyle.Fill;
        panel3.WrapContents = true;
        panel3.Margin = Padding.Empty;
        rbtPersonelEgitimGorevlisiEvet.Text = "Evet";
        rbtPersonelEgitimGorevlisiEvet.Name = "rbtPersonelEgitimGorevlisiEvet";
        rbtPersonelEgitimGorevlisiEvet.AutoSize = true;
        rbtPersonelEgitimGorevlisiEvet.Anchor = AnchorStyles.Left;
        rbtPersonelEgitimGorevlisiEvet.Margin = new Padding(0, 3, 16, 6);
        rbtPersonelEgitimGorevlisiHayir.Text = "Hayır";
        rbtPersonelEgitimGorevlisiHayir.Name = "rbtPersonelEgitimGorevlisiHayir";
        rbtPersonelEgitimGorevlisiHayir.AutoSize = true;
        rbtPersonelEgitimGorevlisiHayir.Anchor = AnchorStyles.Left;
        rbtPersonelEgitimGorevlisiHayir.Margin = new Padding(0, 3, 16, 6);
        tlpIdentity.Name = "tlpIdentity";
        tlpIdentity.Dock = DockStyle.Fill;
        tlpIdentity.ColumnCount = 2;
        tlpIdentity.RowCount = 9;
        tlpIdentity.Margin = Padding.Empty;
        tlpIdentity.Padding = new Padding(16);
        tlpIdentity.BackColor = Color.White;
        tlpIdentity.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpIdentity.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpIdentity.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpIdentity.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpIdentity.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpIdentity.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpIdentity.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpIdentity.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpIdentity.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpIdentity.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpIdentity.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tlpIdentity.AutoScroll = true;
        txtPersonelAd.PlaceholderText = "Adı";
        txtPersonelAd.Name = "txtPersonelAd";
        txtPersonelAd.Dock = DockStyle.Fill;
        txtPersonelAd.Margin = new Padding(0, 0, 16, 10);
        txtPersonelAd.Size = new Size(260, 32);
        txtPersonelAd.TabIndex = 11;
        txtPersonelAd.Font = new Font("Segoe UI", 10F);
        txtPersonelAd.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelAd.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelAd.Name = "lbl_txtPersonelAd";
        lbl_txtPersonelAd.AutoSize = true;
        lbl_txtPersonelAd.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelAd.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelAd.Text = "Ad *";
        txtPersonelSoyad.PlaceholderText = "Soyadı";
        txtPersonelSoyad.Name = "txtPersonelSoyad";
        txtPersonelSoyad.Dock = DockStyle.Fill;
        txtPersonelSoyad.Margin = new Padding(0, 0, 16, 10);
        txtPersonelSoyad.Size = new Size(260, 32);
        txtPersonelSoyad.TabIndex = 13;
        txtPersonelSoyad.Font = new Font("Segoe UI", 10F);
        txtPersonelSoyad.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelSoyad.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelSoyad.Name = "lbl_txtPersonelSoyad";
        lbl_txtPersonelSoyad.AutoSize = true;
        lbl_txtPersonelSoyad.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelSoyad.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelSoyad.Text = "Soyad *";
        cbxPersonelUyruk.DropDownStyle = ComboBoxStyle.DropDownList;
        cbxPersonelUyruk.Items.AddRange(new object[] { "T.C", "Yabancı" });
        cbxPersonelUyruk.Name = "cbxPersonelUyruk";
        cbxPersonelUyruk.Dock = DockStyle.Fill;
        cbxPersonelUyruk.Margin = new Padding(0, 0, 16, 10);
        cbxPersonelUyruk.Size = new Size(260, 32);
        cbxPersonelUyruk.TabIndex = 15;
        cbxPersonelUyruk.Font = new Font("Segoe UI", 10F);
        cbxPersonelUyruk.ForeColor = Color.FromArgb(37, 54, 75);
        lbl_cbxPersonelUyruk.Name = "lbl_cbxPersonelUyruk";
        lbl_cbxPersonelUyruk.AutoSize = true;
        lbl_cbxPersonelUyruk.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_cbxPersonelUyruk.Margin = new Padding(0, 2, 12, 6);
        lbl_cbxPersonelUyruk.Text = "Uyruk";
        txtPersonelKimlik.Name = "txtPersonelKimlik";
        txtPersonelKimlik.Dock = DockStyle.Fill;
        txtPersonelKimlik.Margin = new Padding(0, 0, 16, 10);
        txtPersonelKimlik.Size = new Size(260, 32);
        txtPersonelKimlik.TabIndex = 17;
        txtPersonelKimlik.Font = new Font("Segoe UI", 10F);
        txtPersonelKimlik.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelKimlik.BorderStyle = BorderStyle.FixedSingle;
        lblKimlikNum.Name = "lblKimlikNum";
        lblKimlikNum.AutoSize = true;
        lblKimlikNum.ForeColor = Color.FromArgb(68, 87, 111);
        lblKimlikNum.Margin = new Padding(0, 2, 12, 6);
        lblKimlikNum.Text = "Kimlik / pasaport numarası *";
        dtpPersonelDG.Name = "dtpPersonelDG";
        dtpPersonelDG.Dock = DockStyle.Fill;
        dtpPersonelDG.Margin = new Padding(0, 0, 16, 10);
        dtpPersonelDG.Size = new Size(260, 32);
        dtpPersonelDG.TabIndex = 19;
        dtpPersonelDG.Font = new Font("Segoe UI", 10F);
        dtpPersonelDG.ForeColor = Color.FromArgb(37, 54, 75);
        dtpPersonelDG.Format = DateTimePickerFormat.Custom;
        dtpPersonelDG.CustomFormat = "dd.MM.yyyy";
        lbl_dtpPersonelDG.Name = "lbl_dtpPersonelDG";
        lbl_dtpPersonelDG.AutoSize = true;
        lbl_dtpPersonelDG.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_dtpPersonelDG.Margin = new Padding(0, 2, 12, 6);
        lbl_dtpPersonelDG.Text = "Doğum tarihi";
        lbl_panel1.Name = "lbl_panel1";
        lbl_panel1.AutoSize = true;
        lbl_panel1.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_panel1.Margin = new Padding(0, 2, 12, 6);
        lbl_panel1.Text = "Cinsiyet";
        lbl_panel2.Name = "lbl_panel2";
        lbl_panel2.AutoSize = true;
        lbl_panel2.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_panel2.Margin = new Padding(0, 2, 12, 6);
        lbl_panel2.Text = "Medeni durum";
        pnlPhoto.Name = "pnlPhoto";
        pnlPhoto.Dock = DockStyle.Fill;
        pnlPhoto.ColumnCount = 1;
        pnlPhoto.RowCount = 4;
        pnlPhoto.Margin = Padding.Empty;
        pnlPhoto.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlPhoto.RowStyles.Add(new RowStyle(SizeType.Absolute, 186F));
        pnlPhoto.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        pnlPhoto.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        pnlPhoto.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlPhoto.Padding = new Padding(12);
        pnlPhoto.BackColor = Color.FromArgb(246, 248, 251);
        pbxPersonelPicture.TabStop = false;
        pbxPersonelPicture.Name = "pbxPersonelPicture";
        pbxPersonelPicture.Dock = DockStyle.Fill;
        pbxPersonelPicture.SizeMode = PictureBoxSizeMode.Zoom;
        pbxPersonelPicture.BackColor = Color.FromArgb(235, 240, 247);
        pbxPersonelPicture.Margin = new Padding(0, 0, 0, 10);
        btnChoosePhoto.Name = "btnChoosePhoto";
        btnChoosePhoto.AutoSize = true;
        btnChoosePhoto.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnChoosePhoto.MinimumSize = new Size(96, 34);
        btnChoosePhoto.Padding = new Padding(12, 4, 12, 4);
        btnChoosePhoto.Margin = new Padding(0, 0, 8, 0);
        btnChoosePhoto.FlatStyle = FlatStyle.Flat;
        btnChoosePhoto.BackColor = Color.FromArgb(246, 248, 251);
        btnChoosePhoto.ForeColor = Color.FromArgb(37, 54, 75);
        btnChoosePhoto.UseVisualStyleBackColor = false;
        btnChoosePhoto.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnChoosePhoto.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnChoosePhoto.Text = "Fotoğraf seç";
        btnRemovePhoto.Name = "btnRemovePhoto";
        btnRemovePhoto.AutoSize = true;
        btnRemovePhoto.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnRemovePhoto.MinimumSize = new Size(96, 34);
        btnRemovePhoto.Padding = new Padding(12, 4, 12, 4);
        btnRemovePhoto.Margin = new Padding(0, 0, 8, 0);
        btnRemovePhoto.FlatStyle = FlatStyle.Flat;
        btnRemovePhoto.BackColor = Color.FromArgb(246, 248, 251);
        btnRemovePhoto.ForeColor = Color.FromArgb(37, 54, 75);
        btnRemovePhoto.UseVisualStyleBackColor = false;
        btnRemovePhoto.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnRemovePhoto.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnRemovePhoto.Text = "Fotoğrafı kaldır";
        lblPhotoStatus.Name = "lblPhotoStatus";
        lblPhotoStatus.ForeColor = Color.FromArgb(68, 87, 111);
        lblPhotoStatus.Margin = new Padding(0, 2, 12, 6);
        lblPhotoStatus.Text = "JPG, PNG veya BMP · En fazla 10 MB\nFotoğraf kayıtla kaydedilir.";
        lblPhotoStatus.Dock = DockStyle.Fill;
        lblPhotoStatus.AutoSize = false;
        pnlIdentity.Name = "pnlIdentity";
        pnlIdentity.Dock = DockStyle.Fill;
        pnlIdentity.ColumnCount = 2;
        pnlIdentity.RowCount = 1;
        pnlIdentity.Margin = Padding.Empty;
        pnlIdentity.BackColor = Color.White;
        pnlIdentity.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlIdentity.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 224F));
        pnlIdentity.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlIdentity.Padding = Padding.Empty;
        tlpContact.Name = "tlpContact";
        tlpContact.Dock = DockStyle.Fill;
        tlpContact.ColumnCount = 2;
        tlpContact.RowCount = 5;
        tlpContact.Margin = Padding.Empty;
        tlpContact.Padding = new Padding(16);
        tlpContact.BackColor = Color.White;
        tlpContact.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpContact.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpContact.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpContact.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpContact.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpContact.RowStyles.Add(new RowStyle(SizeType.Absolute, 130F));
        tlpContact.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tlpContact.AutoScroll = true;
        txtPersonelTel.PlaceholderText = "Telefon Numarası";
        txtPersonelTel.Name = "txtPersonelTel";
        txtPersonelTel.Dock = DockStyle.Fill;
        txtPersonelTel.Margin = new Padding(0, 0, 16, 10);
        txtPersonelTel.Size = new Size(260, 32);
        txtPersonelTel.TabIndex = 30;
        txtPersonelTel.Font = new Font("Segoe UI", 10F);
        txtPersonelTel.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelTel.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelTel.Name = "lbl_txtPersonelTel";
        lbl_txtPersonelTel.AutoSize = true;
        lbl_txtPersonelTel.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelTel.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelTel.Text = "Telefon";
        txtPersonelMail.PlaceholderText = "Mail";
        txtPersonelMail.Name = "txtPersonelMail";
        txtPersonelMail.Dock = DockStyle.Fill;
        txtPersonelMail.Margin = new Padding(0, 0, 16, 10);
        txtPersonelMail.Size = new Size(260, 32);
        txtPersonelMail.TabIndex = 32;
        txtPersonelMail.Font = new Font("Segoe UI", 10F);
        txtPersonelMail.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelMail.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelMail.Name = "lbl_txtPersonelMail";
        lbl_txtPersonelMail.AutoSize = true;
        lbl_txtPersonelMail.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelMail.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelMail.Text = "E-posta *";
        txtPersonelAdres.PlaceholderText = "Adres";
        txtPersonelAdres.Name = "txtPersonelAdres";
        txtPersonelAdres.Dock = DockStyle.Fill;
        txtPersonelAdres.Margin = new Padding(0, 0, 16, 10);
        txtPersonelAdres.Size = new Size(260, 32);
        txtPersonelAdres.TabIndex = 34;
        txtPersonelAdres.Font = new Font("Segoe UI", 10F);
        txtPersonelAdres.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelAdres.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelAdres.Name = "lbl_txtPersonelAdres";
        lbl_txtPersonelAdres.AutoSize = true;
        lbl_txtPersonelAdres.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelAdres.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelAdres.Text = "Adres";
        txtPersonelAdres.Multiline = true;
        txtPersonelAdres.ScrollBars = ScrollBars.Vertical;
        txtPersonelIletişimAcilDurum.PlaceholderText = "Acil Durumda Ulaşılacak Kişi";
        txtPersonelIletişimAcilDurum.Name = "txtPersonelIletişimAcilDurum";
        txtPersonelIletişimAcilDurum.Dock = DockStyle.Fill;
        txtPersonelIletişimAcilDurum.Margin = new Padding(0, 0, 16, 10);
        txtPersonelIletişimAcilDurum.Size = new Size(260, 32);
        txtPersonelIletişimAcilDurum.TabIndex = 36;
        txtPersonelIletişimAcilDurum.Font = new Font("Segoe UI", 10F);
        txtPersonelIletişimAcilDurum.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelIletişimAcilDurum.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelIletişimAcilDurum.Name = "lbl_txtPersonelIletişimAcilDurum";
        lbl_txtPersonelIletişimAcilDurum.AutoSize = true;
        lbl_txtPersonelIletişimAcilDurum.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelIletişimAcilDurum.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelIletişimAcilDurum.Text = "Acil durum iletişimi";
        txtPersonelIletişimAcilDurum.Multiline = true;
        txtPersonelIletişimAcilDurum.ScrollBars = ScrollBars.Vertical;
        tlpWork.Name = "tlpWork";
        tlpWork.Dock = DockStyle.Fill;
        tlpWork.ColumnCount = 2;
        tlpWork.RowCount = 7;
        tlpWork.Margin = Padding.Empty;
        tlpWork.Padding = new Padding(16);
        tlpWork.BackColor = Color.White;
        tlpWork.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpWork.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpWork.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpWork.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpWork.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpWork.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpWork.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpWork.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpWork.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tlpWork.AutoScroll = true;
        dtpPersonelIseBaslamaTarihi.Name = "dtpPersonelIseBaslamaTarihi";
        dtpPersonelIseBaslamaTarihi.Dock = DockStyle.Fill;
        dtpPersonelIseBaslamaTarihi.Margin = new Padding(0, 0, 16, 10);
        dtpPersonelIseBaslamaTarihi.Size = new Size(260, 32);
        dtpPersonelIseBaslamaTarihi.TabIndex = 39;
        dtpPersonelIseBaslamaTarihi.Font = new Font("Segoe UI", 10F);
        dtpPersonelIseBaslamaTarihi.ForeColor = Color.FromArgb(37, 54, 75);
        dtpPersonelIseBaslamaTarihi.Format = DateTimePickerFormat.Custom;
        dtpPersonelIseBaslamaTarihi.CustomFormat = "dd.MM.yyyy";
        lbl_dtpPersonelIseBaslamaTarihi.Name = "lbl_dtpPersonelIseBaslamaTarihi";
        lbl_dtpPersonelIseBaslamaTarihi.AutoSize = true;
        lbl_dtpPersonelIseBaslamaTarihi.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_dtpPersonelIseBaslamaTarihi.Margin = new Padding(0, 2, 12, 6);
        lbl_dtpPersonelIseBaslamaTarihi.Text = "İşe başlama";
        txtPersonelDepartman.PlaceholderText = "Departmanı";
        txtPersonelDepartman.Name = "txtPersonelDepartman";
        txtPersonelDepartman.Dock = DockStyle.Fill;
        txtPersonelDepartman.Margin = new Padding(0, 0, 16, 10);
        txtPersonelDepartman.Size = new Size(260, 32);
        txtPersonelDepartman.TabIndex = 41;
        txtPersonelDepartman.Font = new Font("Segoe UI", 10F);
        txtPersonelDepartman.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelDepartman.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelDepartman.Name = "lbl_txtPersonelDepartman";
        lbl_txtPersonelDepartman.AutoSize = true;
        lbl_txtPersonelDepartman.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelDepartman.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelDepartman.Text = "Departman";
        txtPersonelGorev.PlaceholderText = "Görevi / Ünvanı\n\n";
        txtPersonelGorev.Name = "txtPersonelGorev";
        txtPersonelGorev.Dock = DockStyle.Fill;
        txtPersonelGorev.Margin = new Padding(0, 0, 16, 10);
        txtPersonelGorev.Size = new Size(260, 32);
        txtPersonelGorev.TabIndex = 43;
        txtPersonelGorev.Font = new Font("Segoe UI", 10F);
        txtPersonelGorev.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelGorev.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelGorev.Name = "lbl_txtPersonelGorev";
        lbl_txtPersonelGorev.AutoSize = true;
        lbl_txtPersonelGorev.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelGorev.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelGorev.Text = "Görev";
        txtPersonelPersonelNo.PlaceholderText = "Personel Numarası";
        txtPersonelPersonelNo.Name = "txtPersonelPersonelNo";
        txtPersonelPersonelNo.Dock = DockStyle.Fill;
        txtPersonelPersonelNo.Margin = new Padding(0, 0, 16, 10);
        txtPersonelPersonelNo.Size = new Size(260, 32);
        txtPersonelPersonelNo.TabIndex = 45;
        txtPersonelPersonelNo.Font = new Font("Segoe UI", 10F);
        txtPersonelPersonelNo.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelPersonelNo.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelPersonelNo.Name = "lbl_txtPersonelPersonelNo";
        lbl_txtPersonelPersonelNo.AutoSize = true;
        lbl_txtPersonelPersonelNo.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelPersonelNo.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelPersonelNo.Text = "Personel numarası";
        cbxPersonelCalismaSekli.Name = "cbxPersonelCalismaSekli";
        cbxPersonelCalismaSekli.Dock = DockStyle.Fill;
        cbxPersonelCalismaSekli.Margin = new Padding(0, 0, 16, 10);
        cbxPersonelCalismaSekli.Size = new Size(260, 32);
        cbxPersonelCalismaSekli.TabIndex = 47;
        cbxPersonelCalismaSekli.Font = new Font("Segoe UI", 10F);
        cbxPersonelCalismaSekli.ForeColor = Color.FromArgb(37, 54, 75);
        lbl_cbxPersonelCalismaSekli.Name = "lbl_cbxPersonelCalismaSekli";
        lbl_cbxPersonelCalismaSekli.AutoSize = true;
        lbl_cbxPersonelCalismaSekli.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_cbxPersonelCalismaSekli.Margin = new Padding(0, 2, 12, 6);
        lbl_cbxPersonelCalismaSekli.Text = "Çalışma şekli";
        lbl_panel3.Name = "lbl_panel3";
        lbl_panel3.AutoSize = true;
        lbl_panel3.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_panel3.Margin = new Padding(0, 2, 12, 6);
        lbl_panel3.Text = "Eğitim görevlisi";
        tlpEducation.Name = "tlpEducation";
        tlpEducation.Dock = DockStyle.Fill;
        tlpEducation.ColumnCount = 2;
        tlpEducation.RowCount = 7;
        tlpEducation.Margin = Padding.Empty;
        tlpEducation.Padding = new Padding(16);
        tlpEducation.BackColor = Color.White;
        tlpEducation.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpEducation.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpEducation.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpEducation.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpEducation.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpEducation.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpEducation.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpEducation.RowStyles.Add(new RowStyle(SizeType.Absolute, 120F));
        tlpEducation.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tlpEducation.AutoScroll = true;
        cbxPersonelEgitimDurumu.Items.AddRange(new object[] { "Okuryazar Değil", "İlkokul Mezunu ", "Ortaokul Mezunu", "Lise Mezunu", "Önlisans (Devam Ediyor)", "Lisans (Devam Ediyor)", "Yüksek Lisans(Devam Ediyor)", "Doktora (Devam Ediyor)", "Önlisans Mezunu", "Lisans Mezunu", "Yüksek Lisans", "Doktora " });
        cbxPersonelEgitimDurumu.Name = "cbxPersonelEgitimDurumu";
        cbxPersonelEgitimDurumu.Dock = DockStyle.Fill;
        cbxPersonelEgitimDurumu.Margin = new Padding(0, 0, 16, 10);
        cbxPersonelEgitimDurumu.Size = new Size(260, 32);
        cbxPersonelEgitimDurumu.TabIndex = 51;
        cbxPersonelEgitimDurumu.Font = new Font("Segoe UI", 10F);
        cbxPersonelEgitimDurumu.ForeColor = Color.FromArgb(37, 54, 75);
        lbl_cbxPersonelEgitimDurumu.Name = "lbl_cbxPersonelEgitimDurumu";
        lbl_cbxPersonelEgitimDurumu.AutoSize = true;
        lbl_cbxPersonelEgitimDurumu.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_cbxPersonelEgitimDurumu.Margin = new Padding(0, 2, 12, 6);
        lbl_cbxPersonelEgitimDurumu.Text = "Eğitim durumu";
        cbxPersonelUniversite.Name = "cbxPersonelUniversite";
        cbxPersonelUniversite.Dock = DockStyle.Fill;
        cbxPersonelUniversite.Margin = new Padding(0, 0, 16, 10);
        cbxPersonelUniversite.Size = new Size(260, 32);
        cbxPersonelUniversite.TabIndex = 53;
        cbxPersonelUniversite.Font = new Font("Segoe UI", 10F);
        cbxPersonelUniversite.ForeColor = Color.FromArgb(37, 54, 75);
        lbl_cbxPersonelUniversite.Name = "lbl_cbxPersonelUniversite";
        lbl_cbxPersonelUniversite.AutoSize = true;
        lbl_cbxPersonelUniversite.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_cbxPersonelUniversite.Margin = new Padding(0, 2, 12, 6);
        lbl_cbxPersonelUniversite.Text = "Üniversite";
        txtPersonelUniBolum.PlaceholderText = "Bölümü";
        txtPersonelUniBolum.Name = "txtPersonelUniBolum";
        txtPersonelUniBolum.Dock = DockStyle.Fill;
        txtPersonelUniBolum.Margin = new Padding(0, 0, 16, 10);
        txtPersonelUniBolum.Size = new Size(260, 32);
        txtPersonelUniBolum.TabIndex = 55;
        txtPersonelUniBolum.Font = new Font("Segoe UI", 10F);
        txtPersonelUniBolum.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelUniBolum.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelUniBolum.Name = "lbl_txtPersonelUniBolum";
        lbl_txtPersonelUniBolum.AutoSize = true;
        lbl_txtPersonelUniBolum.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelUniBolum.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelUniBolum.Text = "Bölüm";
        txtPersonelYabanciDil.Multiline = true;
        txtPersonelYabanciDil.PlaceholderText = "Yabancı Dil Bilgisi\n\n";
        txtPersonelYabanciDil.Name = "txtPersonelYabanciDil";
        txtPersonelYabanciDil.Dock = DockStyle.Fill;
        txtPersonelYabanciDil.Margin = new Padding(0, 0, 16, 10);
        txtPersonelYabanciDil.Size = new Size(260, 32);
        txtPersonelYabanciDil.TabIndex = 57;
        txtPersonelYabanciDil.Font = new Font("Segoe UI", 10F);
        txtPersonelYabanciDil.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelYabanciDil.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelYabanciDil.Name = "lbl_txtPersonelYabanciDil";
        lbl_txtPersonelYabanciDil.AutoSize = true;
        lbl_txtPersonelYabanciDil.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelYabanciDil.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelYabanciDil.Text = "Yabancı dil";
        txtPersonelSertifika.PlaceholderText = "Sertifikalar ve Eğitimler";
        txtPersonelSertifika.Name = "txtPersonelSertifika";
        txtPersonelSertifika.Dock = DockStyle.Fill;
        txtPersonelSertifika.Margin = new Padding(0, 0, 16, 10);
        txtPersonelSertifika.Size = new Size(260, 32);
        txtPersonelSertifika.TabIndex = 59;
        txtPersonelSertifika.Font = new Font("Segoe UI", 10F);
        txtPersonelSertifika.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelSertifika.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelSertifika.Name = "lbl_txtPersonelSertifika";
        lbl_txtPersonelSertifika.AutoSize = true;
        lbl_txtPersonelSertifika.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelSertifika.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelSertifika.Text = "Sertifikalar";
        txtPersonelSertifika.Multiline = true;
        txtPersonelSertifika.ScrollBars = ScrollBars.Vertical;
        tlpSalary.Name = "tlpSalary";
        tlpSalary.Dock = DockStyle.Fill;
        tlpSalary.ColumnCount = 2;
        tlpSalary.RowCount = 9;
        tlpSalary.Margin = Padding.Empty;
        tlpSalary.Padding = new Padding(16);
        tlpSalary.BackColor = Color.White;
        tlpSalary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpSalary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpSalary.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpSalary.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpSalary.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpSalary.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpSalary.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpSalary.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpSalary.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpSalary.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpSalary.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tlpSalary.AutoScroll = true;
        txtPersonelMaas.PlaceholderText = "Maaş";
        txtPersonelMaas.Name = "txtPersonelMaas";
        txtPersonelMaas.Dock = DockStyle.Fill;
        txtPersonelMaas.Margin = new Padding(0, 0, 16, 10);
        txtPersonelMaas.Size = new Size(260, 32);
        txtPersonelMaas.TabIndex = 62;
        txtPersonelMaas.Font = new Font("Segoe UI", 10F);
        txtPersonelMaas.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelMaas.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelMaas.Name = "lbl_txtPersonelMaas";
        lbl_txtPersonelMaas.AutoSize = true;
        lbl_txtPersonelMaas.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelMaas.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelMaas.Text = "Maaş";
        txtPersonelPrimVeEk.PlaceholderText = "Prim ve Ek Ödemeler";
        txtPersonelPrimVeEk.Name = "txtPersonelPrimVeEk";
        txtPersonelPrimVeEk.Dock = DockStyle.Fill;
        txtPersonelPrimVeEk.Margin = new Padding(0, 0, 16, 10);
        txtPersonelPrimVeEk.Size = new Size(260, 32);
        txtPersonelPrimVeEk.TabIndex = 64;
        txtPersonelPrimVeEk.Font = new Font("Segoe UI", 10F);
        txtPersonelPrimVeEk.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelPrimVeEk.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelPrimVeEk.Name = "lbl_txtPersonelPrimVeEk";
        lbl_txtPersonelPrimVeEk.AutoSize = true;
        lbl_txtPersonelPrimVeEk.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelPrimVeEk.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelPrimVeEk.Text = "Prim / ek ödeme";
        txtPersonelYemekYol.PlaceholderText = "Yemek ve Yol Yardımı";
        txtPersonelYemekYol.Name = "txtPersonelYemekYol";
        txtPersonelYemekYol.Dock = DockStyle.Fill;
        txtPersonelYemekYol.Margin = new Padding(0, 0, 16, 10);
        txtPersonelYemekYol.Size = new Size(260, 32);
        txtPersonelYemekYol.TabIndex = 66;
        txtPersonelYemekYol.Font = new Font("Segoe UI", 10F);
        txtPersonelYemekYol.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelYemekYol.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelYemekYol.Name = "lbl_txtPersonelYemekYol";
        lbl_txtPersonelYemekYol.AutoSize = true;
        lbl_txtPersonelYemekYol.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelYemekYol.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelYemekYol.Text = "Yemek / yol";
        cbxPersonelSigorta.Name = "cbxPersonelSigorta";
        cbxPersonelSigorta.Dock = DockStyle.Fill;
        cbxPersonelSigorta.Margin = new Padding(0, 0, 16, 10);
        cbxPersonelSigorta.Size = new Size(260, 32);
        cbxPersonelSigorta.TabIndex = 68;
        cbxPersonelSigorta.Font = new Font("Segoe UI", 10F);
        cbxPersonelSigorta.ForeColor = Color.FromArgb(37, 54, 75);
        lbl_cbxPersonelSigorta.Name = "lbl_cbxPersonelSigorta";
        lbl_cbxPersonelSigorta.AutoSize = true;
        lbl_cbxPersonelSigorta.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_cbxPersonelSigorta.Margin = new Padding(0, 2, 12, 6);
        lbl_cbxPersonelSigorta.Text = "Sigorta türü";
        txtPersonelSGKSicilNum.PlaceholderText = "SGK Sicil Numarası";
        txtPersonelSGKSicilNum.Name = "txtPersonelSGKSicilNum";
        txtPersonelSGKSicilNum.Dock = DockStyle.Fill;
        txtPersonelSGKSicilNum.Margin = new Padding(0, 0, 16, 10);
        txtPersonelSGKSicilNum.Size = new Size(260, 32);
        txtPersonelSGKSicilNum.TabIndex = 70;
        txtPersonelSGKSicilNum.Font = new Font("Segoe UI", 10F);
        txtPersonelSGKSicilNum.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelSGKSicilNum.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelSGKSicilNum.Name = "lbl_txtPersonelSGKSicilNum";
        lbl_txtPersonelSGKSicilNum.AutoSize = true;
        lbl_txtPersonelSGKSicilNum.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelSGKSicilNum.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelSGKSicilNum.Text = "SGK sicil numarası";
        txtPersonelSaglikSigorta.PlaceholderText = "Sağlık Sigortası Bilgileri\n\n";
        txtPersonelSaglikSigorta.Name = "txtPersonelSaglikSigorta";
        txtPersonelSaglikSigorta.Dock = DockStyle.Fill;
        txtPersonelSaglikSigorta.Margin = new Padding(0, 0, 16, 10);
        txtPersonelSaglikSigorta.Size = new Size(260, 32);
        txtPersonelSaglikSigorta.TabIndex = 72;
        txtPersonelSaglikSigorta.Font = new Font("Segoe UI", 10F);
        txtPersonelSaglikSigorta.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelSaglikSigorta.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelSaglikSigorta.Name = "lbl_txtPersonelSaglikSigorta";
        lbl_txtPersonelSaglikSigorta.AutoSize = true;
        lbl_txtPersonelSaglikSigorta.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelSaglikSigorta.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelSaglikSigorta.Text = "Sağlık sigortası";
        txtPersonelEmeklilik.PlaceholderText = "Emeklilik Bilgileri\n\n";
        txtPersonelEmeklilik.Name = "txtPersonelEmeklilik";
        txtPersonelEmeklilik.Dock = DockStyle.Fill;
        txtPersonelEmeklilik.Margin = new Padding(0, 0, 16, 10);
        txtPersonelEmeklilik.Size = new Size(260, 32);
        txtPersonelEmeklilik.TabIndex = 74;
        txtPersonelEmeklilik.Font = new Font("Segoe UI", 10F);
        txtPersonelEmeklilik.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelEmeklilik.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelEmeklilik.Name = "lbl_txtPersonelEmeklilik";
        lbl_txtPersonelEmeklilik.AutoSize = true;
        lbl_txtPersonelEmeklilik.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelEmeklilik.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelEmeklilik.Text = "Emeklilik";
        tlpLeave.Name = "tlpLeave";
        tlpLeave.Dock = DockStyle.Fill;
        tlpLeave.ColumnCount = 2;
        tlpLeave.RowCount = 5;
        tlpLeave.Margin = Padding.Empty;
        tlpLeave.Padding = new Padding(16);
        tlpLeave.BackColor = Color.White;
        tlpLeave.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpLeave.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        tlpLeave.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpLeave.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        tlpLeave.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        tlpLeave.RowStyles.Add(new RowStyle(SizeType.Absolute, 130F));
        tlpLeave.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tlpLeave.AutoScroll = true;
        cbxPersoneIIsAyrıldı.Text = "İşten Ayrıldı";
        cbxPersoneIIsAyrıldı.Name = "cbxPersoneIIsAyrıldı";
        cbxPersoneIIsAyrıldı.AutoSize = true;
        cbxPersoneIIsAyrıldı.Anchor = AnchorStyles.Left;
        cbxPersoneIIsAyrıldı.Margin = new Padding(0, 3, 16, 6);
        lbl_cbxPersoneIIsAyrıldı.Name = "lbl_cbxPersoneIIsAyrıldı";
        lbl_cbxPersoneIIsAyrıldı.AutoSize = true;
        lbl_cbxPersoneIIsAyrıldı.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_cbxPersoneIIsAyrıldı.Margin = new Padding(0, 2, 12, 6);
        lbl_cbxPersoneIIsAyrıldı.Text = "İşten ayrıldı";
        dtpPersonelCıkısTarihi.Name = "dtpPersonelCıkısTarihi";
        dtpPersonelCıkısTarihi.Dock = DockStyle.Fill;
        dtpPersonelCıkısTarihi.Margin = new Padding(0, 0, 16, 10);
        dtpPersonelCıkısTarihi.Size = new Size(260, 32);
        dtpPersonelCıkısTarihi.TabIndex = 79;
        dtpPersonelCıkısTarihi.Font = new Font("Segoe UI", 10F);
        dtpPersonelCıkısTarihi.ForeColor = Color.FromArgb(37, 54, 75);
        dtpPersonelCıkısTarihi.Format = DateTimePickerFormat.Custom;
        dtpPersonelCıkısTarihi.CustomFormat = "dd.MM.yyyy";
        lbl_dtpPersonelCıkısTarihi.Name = "lbl_dtpPersonelCıkısTarihi";
        lbl_dtpPersonelCıkısTarihi.AutoSize = true;
        lbl_dtpPersonelCıkısTarihi.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_dtpPersonelCıkısTarihi.Margin = new Padding(0, 2, 12, 6);
        lbl_dtpPersonelCıkısTarihi.Text = "Çıkış tarihi";
        txtPersonelAyrilmaNedeni.PlaceholderText = "Ayrılma Nedeni";
        txtPersonelAyrilmaNedeni.Name = "txtPersonelAyrilmaNedeni";
        txtPersonelAyrilmaNedeni.Dock = DockStyle.Fill;
        txtPersonelAyrilmaNedeni.Margin = new Padding(0, 0, 16, 10);
        txtPersonelAyrilmaNedeni.Size = new Size(260, 32);
        txtPersonelAyrilmaNedeni.TabIndex = 81;
        txtPersonelAyrilmaNedeni.Font = new Font("Segoe UI", 10F);
        txtPersonelAyrilmaNedeni.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelAyrilmaNedeni.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelAyrilmaNedeni.Name = "lbl_txtPersonelAyrilmaNedeni";
        lbl_txtPersonelAyrilmaNedeni.AutoSize = true;
        lbl_txtPersonelAyrilmaNedeni.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelAyrilmaNedeni.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelAyrilmaNedeni.Text = "Ayrılma nedeni";
        txtPersonelAyrilmaNedeni.Multiline = true;
        txtPersonelAyrilmaNedeni.ScrollBars = ScrollBars.Vertical;
        txtPersonelKidemTazminat.PlaceholderText = "Kıdem ve İhbar Tazminatı\n\n";
        txtPersonelKidemTazminat.Name = "txtPersonelKidemTazminat";
        txtPersonelKidemTazminat.Dock = DockStyle.Fill;
        txtPersonelKidemTazminat.Margin = new Padding(0, 0, 16, 10);
        txtPersonelKidemTazminat.Size = new Size(260, 32);
        txtPersonelKidemTazminat.TabIndex = 83;
        txtPersonelKidemTazminat.Font = new Font("Segoe UI", 10F);
        txtPersonelKidemTazminat.ForeColor = Color.FromArgb(37, 54, 75);
        txtPersonelKidemTazminat.BorderStyle = BorderStyle.FixedSingle;
        lbl_txtPersonelKidemTazminat.Name = "lbl_txtPersonelKidemTazminat";
        lbl_txtPersonelKidemTazminat.AutoSize = true;
        lbl_txtPersonelKidemTazminat.ForeColor = Color.FromArgb(68, 87, 111);
        lbl_txtPersonelKidemTazminat.Margin = new Padding(0, 2, 12, 6);
        lbl_txtPersonelKidemTazminat.Text = "Kıdem tazminatı";
        tabPersonnelDetails.Name = "tabPersonnelDetails";
        tabPersonnelDetails.Dock = DockStyle.Fill;
        tabPersonnelDetails.Padding = new Point(14, 7);
        tabPersonnelDetails.SelectedIndex = 0;
        tabIdentity.Name = "tabIdentity";
        tabIdentity.Text = "Kimlik Bilgileri";
        tabIdentity.Padding = new Padding(4);
        tabIdentity.BackColor = Color.White;
        tabIdentity.AutoScroll = true;
        tabContact.Name = "tabContact";
        tabContact.Text = "İletişim";
        tabContact.Padding = new Padding(4);
        tabContact.BackColor = Color.White;
        tabContact.AutoScroll = true;
        tabWork.Name = "tabWork";
        tabWork.Text = "Çalışma Bilgileri";
        tabWork.Padding = new Padding(4);
        tabWork.BackColor = Color.White;
        tabWork.AutoScroll = true;
        tabEducation.Name = "tabEducation";
        tabEducation.Text = "Eğitim";
        tabEducation.Padding = new Padding(4);
        tabEducation.BackColor = Color.White;
        tabEducation.AutoScroll = true;
        tabSalary.Name = "tabSalary";
        tabSalary.Text = "Ücret ve Sigorta";
        tabSalary.Padding = new Padding(4);
        tabSalary.BackColor = Color.White;
        tabSalary.AutoScroll = true;
        tabLeave.Name = "tabLeave";
        tabLeave.Text = "İşten Ayrılma";
        tabLeave.Padding = new Padding(4);
        tabLeave.BackColor = Color.White;
        tabLeave.AutoScroll = true;
        pnlRoot.Name = "pnlRoot";
        pnlRoot.Dock = DockStyle.Fill;
        pnlRoot.ColumnCount = 1;
        pnlRoot.RowCount = 3;
        pnlRoot.Margin = Padding.Empty;
        pnlRoot.BackColor = Color.White;
        pnlRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 62F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlRoot.Padding = Padding.Empty;
        pnlHeader.Name = "pnlHeader";
        pnlHeader.Dock = DockStyle.Fill;
        pnlHeader.ColumnCount = 1;
        pnlHeader.RowCount = 2;
        pnlHeader.Margin = Padding.Empty;
        pnlHeader.BackColor = Color.White;
        pnlHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlHeader.Padding = new Padding(16, 6, 16, 0);
        lblTitle.Name = "lblTitle";
        lblTitle.ForeColor = Color.FromArgb(68, 87, 111);
        lblTitle.Margin = new Padding(0, 2, 12, 6);
        lblTitle.Text = "Personel Kartı";
        lblTitle.Font = new Font("Segoe UI Semibold", 15F);
        lblTitle.AutoSize = true;
        lblSubtitle.Name = "lblSubtitle";
        lblSubtitle.ForeColor = Color.FromArgb(68, 87, 111);
        lblSubtitle.Margin = new Padding(0, 2, 12, 6);
        lblSubtitle.Text = "Bilgileri düzenleyin; değişikliklerinizi kaydedin.";
        lblSubtitle.AutoSize = true;
        pnlCommandBar.Name = "pnlCommandBar";
        pnlCommandBar.Dock = DockStyle.Top;
        pnlCommandBar.AutoSize = true;
        pnlCommandBar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlCommandBar.WrapContents = true;
        pnlCommandBar.Padding = new Padding(16, 8, 8, 8);
        pnlCommandBar.Margin = Padding.Empty;
        pnlCommandBar.BackColor = Color.White;
        btnPersonelKaydet.Name = "btnPersonelKaydet";
        btnPersonelKaydet.AutoSize = true;
        btnPersonelKaydet.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnPersonelKaydet.MinimumSize = new Size(96, 34);
        btnPersonelKaydet.Padding = new Padding(12, 4, 12, 4);
        btnPersonelKaydet.Margin = new Padding(0, 0, 8, 0);
        btnPersonelKaydet.FlatStyle = FlatStyle.Flat;
        btnPersonelKaydet.BackColor = Color.FromArgb(40, 99, 163);
        btnPersonelKaydet.ForeColor = Color.White;
        btnPersonelKaydet.UseVisualStyleBackColor = false;
        btnPersonelKaydet.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnPersonelKaydet.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnPersonelKaydet.Text = "Kaydet";
        btnPersonelGuncelle.Name = "btnPersonelGuncelle";
        btnPersonelGuncelle.AutoSize = true;
        btnPersonelGuncelle.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnPersonelGuncelle.MinimumSize = new Size(96, 34);
        btnPersonelGuncelle.Padding = new Padding(12, 4, 12, 4);
        btnPersonelGuncelle.Margin = new Padding(0, 0, 8, 0);
        btnPersonelGuncelle.FlatStyle = FlatStyle.Flat;
        btnPersonelGuncelle.BackColor = Color.FromArgb(246, 248, 251);
        btnPersonelGuncelle.ForeColor = Color.FromArgb(37, 54, 75);
        btnPersonelGuncelle.UseVisualStyleBackColor = false;
        btnPersonelGuncelle.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnPersonelGuncelle.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnPersonelGuncelle.Text = "Güncelle";
        btnPersonelSil.Name = "btnPersonelSil";
        btnPersonelSil.AutoSize = true;
        btnPersonelSil.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnPersonelSil.MinimumSize = new Size(96, 34);
        btnPersonelSil.Padding = new Padding(12, 4, 12, 4);
        btnPersonelSil.Margin = new Padding(0, 0, 8, 0);
        btnPersonelSil.FlatStyle = FlatStyle.Flat;
        btnPersonelSil.BackColor = Color.FromArgb(246, 248, 251);
        btnPersonelSil.ForeColor = Color.FromArgb(37, 54, 75);
        btnPersonelSil.UseVisualStyleBackColor = false;
        btnPersonelSil.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnPersonelSil.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnPersonelSil.Text = "Pasife al";
        btnPersonelTemizle.Name = "btnPersonelTemizle";
        btnPersonelTemizle.AutoSize = true;
        btnPersonelTemizle.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnPersonelTemizle.MinimumSize = new Size(96, 34);
        btnPersonelTemizle.Padding = new Padding(12, 4, 12, 4);
        btnPersonelTemizle.Margin = new Padding(0, 0, 8, 0);
        btnPersonelTemizle.FlatStyle = FlatStyle.Flat;
        btnPersonelTemizle.BackColor = Color.FromArgb(246, 248, 251);
        btnPersonelTemizle.ForeColor = Color.FromArgb(37, 54, 75);
        btnPersonelTemizle.UseVisualStyleBackColor = false;
        btnPersonelTemizle.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnPersonelTemizle.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnPersonelTemizle.Text = "Temizle";
        btnClose.Name = "btnClose";
        btnClose.AutoSize = true;
        btnClose.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btnClose.MinimumSize = new Size(96, 34);
        btnClose.Padding = new Padding(12, 4, 12, 4);
        btnClose.Margin = new Padding(0, 0, 8, 0);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.BackColor = Color.FromArgb(246, 248, 251);
        btnClose.ForeColor = Color.FromArgb(37, 54, 75);
        btnClose.UseVisualStyleBackColor = false;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(220, 226, 233);
        btnClose.FlatAppearance.MouseOverBackColor = Color.FromArgb(221, 237, 253);
        btnClose.Text = "Kapat";
        panel1.Controls.Add(rbtPersonelErkek);
        panel1.Controls.Add(rbtPersonelKadin);
        panel2.Controls.Add(rbtPersonelEvli);
        panel2.Controls.Add(rbtPersonelBekar);
        panel3.Controls.Add(rbtPersonelEgitimGorevlisiEvet);
        panel3.Controls.Add(rbtPersonelEgitimGorevlisiHayir);
        tlpIdentity.Controls.Add(lbl_txtPersonelAd, 0, 0);
        tlpIdentity.Controls.Add(txtPersonelAd, 0, 1);
        tlpIdentity.Controls.Add(lbl_txtPersonelSoyad, 1, 0);
        tlpIdentity.Controls.Add(txtPersonelSoyad, 1, 1);
        tlpIdentity.Controls.Add(lbl_cbxPersonelUyruk, 0, 2);
        tlpIdentity.Controls.Add(cbxPersonelUyruk, 0, 3);
        tlpIdentity.Controls.Add(lblKimlikNum, 1, 2);
        tlpIdentity.Controls.Add(txtPersonelKimlik, 1, 3);
        tlpIdentity.Controls.Add(lbl_dtpPersonelDG, 0, 4);
        tlpIdentity.Controls.Add(dtpPersonelDG, 0, 5);
        tlpIdentity.Controls.Add(lbl_panel1, 1, 4);
        tlpIdentity.Controls.Add(panel1, 1, 5);
        tlpIdentity.Controls.Add(lbl_panel2, 0, 6);
        tlpIdentity.Controls.Add(panel2, 0, 7);
        pnlPhoto.Controls.Add(pbxPersonelPicture, 0, 0);
        pnlPhoto.Controls.Add(btnChoosePhoto, 0, 1);
        pnlPhoto.Controls.Add(btnRemovePhoto, 0, 2);
        pnlPhoto.Controls.Add(lblPhotoStatus, 0, 3);
        pnlIdentity.Controls.Add(tlpIdentity, 0, 0);
        pnlIdentity.Controls.Add(pnlPhoto, 1, 0);
        tlpContact.Controls.Add(lbl_txtPersonelTel, 0, 0);
        tlpContact.Controls.Add(txtPersonelTel, 0, 1);
        tlpContact.Controls.Add(lbl_txtPersonelMail, 1, 0);
        tlpContact.Controls.Add(txtPersonelMail, 1, 1);
        tlpContact.Controls.Add(lbl_txtPersonelAdres, 0, 2);
        tlpContact.Controls.Add(txtPersonelAdres, 0, 3);
        tlpContact.Controls.Add(lbl_txtPersonelIletişimAcilDurum, 1, 2);
        tlpContact.Controls.Add(txtPersonelIletişimAcilDurum, 1, 3);
        tlpWork.Controls.Add(lbl_dtpPersonelIseBaslamaTarihi, 0, 0);
        tlpWork.Controls.Add(dtpPersonelIseBaslamaTarihi, 0, 1);
        tlpWork.Controls.Add(lbl_txtPersonelDepartman, 1, 0);
        tlpWork.Controls.Add(txtPersonelDepartman, 1, 1);
        tlpWork.Controls.Add(lbl_txtPersonelGorev, 0, 2);
        tlpWork.Controls.Add(txtPersonelGorev, 0, 3);
        tlpWork.Controls.Add(lbl_txtPersonelPersonelNo, 1, 2);
        tlpWork.Controls.Add(txtPersonelPersonelNo, 1, 3);
        tlpWork.Controls.Add(lbl_cbxPersonelCalismaSekli, 0, 4);
        tlpWork.Controls.Add(cbxPersonelCalismaSekli, 0, 5);
        tlpWork.Controls.Add(lbl_panel3, 1, 4);
        tlpWork.Controls.Add(panel3, 1, 5);
        tlpEducation.Controls.Add(lbl_cbxPersonelEgitimDurumu, 0, 0);
        tlpEducation.Controls.Add(cbxPersonelEgitimDurumu, 0, 1);
        tlpEducation.Controls.Add(lbl_cbxPersonelUniversite, 1, 0);
        tlpEducation.Controls.Add(cbxPersonelUniversite, 1, 1);
        tlpEducation.Controls.Add(lbl_txtPersonelUniBolum, 0, 2);
        tlpEducation.Controls.Add(txtPersonelUniBolum, 0, 3);
        tlpEducation.Controls.Add(lbl_txtPersonelYabanciDil, 1, 2);
        tlpEducation.Controls.Add(txtPersonelYabanciDil, 1, 3);
        tlpEducation.Controls.Add(lbl_txtPersonelSertifika, 0, 4);
        tlpEducation.Controls.Add(txtPersonelSertifika, 0, 5);
        tlpSalary.Controls.Add(lbl_txtPersonelMaas, 0, 0);
        tlpSalary.Controls.Add(txtPersonelMaas, 0, 1);
        tlpSalary.Controls.Add(lbl_txtPersonelPrimVeEk, 1, 0);
        tlpSalary.Controls.Add(txtPersonelPrimVeEk, 1, 1);
        tlpSalary.Controls.Add(lbl_txtPersonelYemekYol, 0, 2);
        tlpSalary.Controls.Add(txtPersonelYemekYol, 0, 3);
        tlpSalary.Controls.Add(lbl_cbxPersonelSigorta, 1, 2);
        tlpSalary.Controls.Add(cbxPersonelSigorta, 1, 3);
        tlpSalary.Controls.Add(lbl_txtPersonelSGKSicilNum, 0, 4);
        tlpSalary.Controls.Add(txtPersonelSGKSicilNum, 0, 5);
        tlpSalary.Controls.Add(lbl_txtPersonelSaglikSigorta, 1, 4);
        tlpSalary.Controls.Add(txtPersonelSaglikSigorta, 1, 5);
        tlpSalary.Controls.Add(lbl_txtPersonelEmeklilik, 0, 6);
        tlpSalary.Controls.Add(txtPersonelEmeklilik, 0, 7);
        tlpLeave.Controls.Add(lbl_cbxPersoneIIsAyrıldı, 0, 0);
        tlpLeave.Controls.Add(cbxPersoneIIsAyrıldı, 0, 1);
        tlpLeave.Controls.Add(lbl_dtpPersonelCıkısTarihi, 1, 0);
        tlpLeave.Controls.Add(dtpPersonelCıkısTarihi, 1, 1);
        tlpLeave.Controls.Add(lbl_txtPersonelAyrilmaNedeni, 0, 2);
        tlpLeave.Controls.Add(txtPersonelAyrilmaNedeni, 0, 3);
        tlpLeave.Controls.Add(lbl_txtPersonelKidemTazminat, 1, 2);
        tlpLeave.Controls.Add(txtPersonelKidemTazminat, 1, 3);
        tabIdentity.Controls.Add(pnlIdentity);
        tabPersonnelDetails.Controls.Add(tabIdentity);
        tabContact.Controls.Add(tlpContact);
        tabPersonnelDetails.Controls.Add(tabContact);
        tabWork.Controls.Add(tlpWork);
        tabPersonnelDetails.Controls.Add(tabWork);
        tabEducation.Controls.Add(tlpEducation);
        tabPersonnelDetails.Controls.Add(tabEducation);
        tabSalary.Controls.Add(tlpSalary);
        tabPersonnelDetails.Controls.Add(tabSalary);
        tabLeave.Controls.Add(tlpLeave);
        tabPersonnelDetails.Controls.Add(tabLeave);
        pnlHeader.Controls.Add(lblTitle, 0, 0);
        pnlHeader.Controls.Add(lblSubtitle, 0, 1);
        pnlRoot.Controls.Add(pnlHeader, 0, 0);
        pnlCommandBar.Controls.Add(btnPersonelKaydet);
        pnlCommandBar.Controls.Add(btnPersonelGuncelle);
        pnlCommandBar.Controls.Add(btnPersonelSil);
        pnlCommandBar.Controls.Add(btnPersonelTemizle);
        pnlCommandBar.Controls.Add(btnClose);
        pnlRoot.Controls.Add(pnlCommandBar, 0, 1);
        pnlRoot.Controls.Add(tabPersonnelDetails, 0, 2);
        Controls.Add(pnlRoot);
        cbxPersonelUyruk.SelectedIndexChanged += cbxPersonelUyruk_SelectedIndexChanged;
        btnChoosePhoto.Click += ChoosePhoto_Click;
        btnRemovePhoto.Click += RemovePhoto_Click;
        cbxPersoneIIsAyrıldı.CheckedChanged += cbxPersoneIIsAyrıldı_CheckedChanged;
        btnPersonelKaydet.Click += btnPersonelKaydet_Click;
        btnPersonelGuncelle.Click += btnPersonelGuncelle_Click;
        btnPersonelSil.Click += btnPersonelSil_Click;
        btnPersonelTemizle.Click += btnPersonelTemizle_Click;
        btnClose.Click += CloseRecord_Click;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.White;
        ClientSize = new Size(1120, 760);
        MinimumSize = new Size(720, 520);
        StartPosition = FormStartPosition.CenterParent;
        KeyPreview = true;
        Name = "PersonelForm";
        Text = "Personel Kartı";
        Load += PersonelForm_Load;
        ((System.ComponentModel.ISupportInitialize)pbxPersonelPicture).EndInit();
        pnlCommandBar.ResumeLayout(false);
        pnlCommandBar.PerformLayout();
        pnlHeader.ResumeLayout(false);
        pnlHeader.PerformLayout();
        pnlRoot.ResumeLayout(false);
        pnlRoot.PerformLayout();
        tabLeave.ResumeLayout(false);
        tabLeave.PerformLayout();
        tabSalary.ResumeLayout(false);
        tabSalary.PerformLayout();
        tabEducation.ResumeLayout(false);
        tabEducation.PerformLayout();
        tabWork.ResumeLayout(false);
        tabWork.PerformLayout();
        tabContact.ResumeLayout(false);
        tabContact.PerformLayout();
        tabIdentity.ResumeLayout(false);
        tabIdentity.PerformLayout();
        tabPersonnelDetails.ResumeLayout(false);
        tabPersonnelDetails.PerformLayout();
        tlpLeave.ResumeLayout(false);
        tlpLeave.PerformLayout();
        tlpSalary.ResumeLayout(false);
        tlpSalary.PerformLayout();
        tlpEducation.ResumeLayout(false);
        tlpEducation.PerformLayout();
        tlpWork.ResumeLayout(false);
        tlpWork.PerformLayout();
        tlpContact.ResumeLayout(false);
        tlpContact.PerformLayout();
        pnlIdentity.ResumeLayout(false);
        pnlIdentity.PerformLayout();
        pnlPhoto.ResumeLayout(false);
        pnlPhoto.PerformLayout();
        tlpIdentity.ResumeLayout(false);
        tlpIdentity.PerformLayout();
        panel3.ResumeLayout(false);
        panel3.PerformLayout();
        panel2.ResumeLayout(false);
        panel2.PerformLayout();
        panel1.ResumeLayout(false);
        panel1.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }
    #endregion
}
